# 01b - Automatic Player Collection

The first data collection notebook used a small manually selected player list.

That sample was useful for testing the pipeline, but it is too small and biased for meaningful clustering.

This notebook automatically collects a larger and more diverse set of Old School RuneScape player names using random partial username searches.

After collecting player names, the notebook downloads public OSRS Hiscores data for each player and saves the result as a structured dataset.

## 1. Import required packages

The following packages are used for:

- API requests,
- data handling,
- random search term generation,
- waiting between requests,
- file path management.

In [9]:
import requests
import pandas as pd
import time
import random
import string

from pathlib import Path

## 2. Project paths

The collected dataset will be saved into the `data/processed` folder.

The folder structure follows the project layout used throughout the repository.

In [10]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

PROCESSED_DATA_DIR

WindowsPath('C:/Projects/osrs-player-segmentation/data/processed')

## 3. Why pseudo-random player collection?

Using only top leaderboard players would introduce strong sampling bias.

Top-ranked players usually have very high levels and similar progression patterns, which would make clustering less meaningful.

Instead, this notebook uses random partial username searches to collect a more diverse set of players.

This is not a perfectly random sample of all OSRS players, but it is more suitable for this project than a top leaderboard sample.

## 4. Generate random username search terms

The player collection process starts by generating random short character combinations.

These terms will be used as partial username searches.

In [11]:
def generate_random_search_terms(
    n_terms=300,
    min_length=2,
    max_length=4,
    random_state=42
):
    """
    Generate random partial username search terms.

    Examples:
    - ab
    - x7
    - kq2
    - 9rs

    These terms are later used to search for OSRS player names.
    """
    random.seed(random_state)

    terms = set()
    characters = string.ascii_lowercase + string.digits

    while len(terms) < n_terms:
        length = random.randint(min_length, max_length)
        term = "".join(random.choice(characters) for _ in range(length))
        terms.add(term)

    return list(terms)

In [12]:
search_terms = generate_random_search_terms(
    n_terms=20,
    min_length=2,
    max_length=4,
    random_state=42
)

search_terms[:10]

['m80o', 'k8pk', 'rak', 'osfo', '6b', '8f1c', 'yr9', 'hbrp', 'xmec', 'ig']

## 5. Search players by partial username

This function sends a request to the Wise Old Man player search endpoint.

For each random search term, it returns matching player names.

In [18]:
def search_wom_players(username_query, limit=20, max_retries=3):
    url = "https://api.wiseoldman.net/v2/players/search"

    params = {
        "username": username_query,
        "limit": limit
    }

    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=15)

            if response.status_code == 429:
                wait_time = 10 * (attempt + 1)
                print(f"Rate limited for '{username_query}'. Waiting {wait_time} seconds...")
                time.sleep(wait_time)
                continue

            response.raise_for_status()
            data = response.json()

            player_names = []

            for item in data:
                username = item.get("displayName") or item.get("username")

                if username:
                    player_names.append(username)

            return player_names

        except requests.RequestException as error:
            print(f"Search failed for query '{username_query}': {error}")
            return []

    print(f"Search skipped after retries: {username_query}")
    return []

In [19]:
test_names = search_wom_players("rs", limit=10)

len(test_names), test_names[:10]

(10,
 ['RsSuomi',
  'Rs Jamal',
  'Rs But Afk',
  'rsvp',
  'Rs Wiki',
  'RS SLAG',
  'Rs Kajcsa',
  'rsyux',
  'RS ape',
  'rs basherr'])

## 6. Collect pseudo-random player names

This function repeatedly generates search terms, queries matching players, and stores unique usernames.

The process stops when the target number of unique players is reached or when all search terms have been used.

In [20]:
def collect_pseudo_random_player_names(
    target_count=500,
    n_search_terms=500,
    results_per_term=20,
    sleep_seconds=0.2,
    random_state=42
):
    """
    Collect a diverse set of OSRS player names using random partial username searches.

    Parameters:
    - target_count: desired number of unique player names
    - n_search_terms: number of generated random search terms
    - results_per_term: maximum number of players returned per search term
    - sleep_seconds: waiting time between API requests
    - random_state: seed for reproducibility

    Returns:
    - list of unique player names
    """
    search_terms = generate_random_search_terms(
        n_terms=n_search_terms,
        min_length=2,
        max_length=4,
        random_state=random_state
    )

    collected_names = []

    for index, term in enumerate(search_terms, start=1):
        print(f"[{index}/{len(search_terms)}] Searching term: {term}")

        names = search_wom_players(
            username_query=term,
            limit=results_per_term
        )

        collected_names.extend(names)
        collected_names = list(dict.fromkeys(collected_names))

        print(f"Collected unique players: {len(collected_names)}")

        if len(collected_names) >= target_count:
            break

        time.sleep(sleep_seconds)

    return collected_names[:target_count]

## 7. Run player name collection

In this step, we collect the player names that will be used for Hiscores data collection.

The target sample size can be adjusted depending on runtime.

In [21]:
player_names = collect_pseudo_random_player_names(
    target_count=1000,
    n_search_terms=2000,
    results_per_term=20,
    sleep_seconds=1.0,
    random_state=42
)

len(player_names), player_names[:20]

[1/2000] Searching term: obb
Collected unique players: 20
[2/2000] Searching term: 7kd6
Collected unique players: 20
[3/2000] Searching term: xpo
Collected unique players: 40
[4/2000] Searching term: i42
Collected unique players: 49
[5/2000] Searching term: zv9d
Collected unique players: 49
[6/2000] Searching term: q3d
Collected unique players: 49
[7/2000] Searching term: ws
Collected unique players: 69
[8/2000] Searching term: dm
Collected unique players: 89
[9/2000] Searching term: 7f7
Collected unique players: 90
[10/2000] Searching term: q2y4
Collected unique players: 90
[11/2000] Searching term: w1d
Collected unique players: 98
[12/2000] Searching term: et32
Collected unique players: 98
[13/2000] Searching term: 9p7k
Collected unique players: 98
[14/2000] Searching term: tbz
Collected unique players: 107
[15/2000] Searching term: z5jr
Collected unique players: 107
[16/2000] Searching term: xi9d
Collected unique players: 107
[17/2000] Searching term: n6s
Collected unique players: 108
[18/2000] Searching term: 0r
Collected unique players: 128
[19/2000] Searching term: g2wo
Collected unique players: 128
[20/2000] Searching term: nv
Collected unique players: 148
[21/2000] Searching term: 51
Rate limited for '51'. Waiting 10 seconds...
Rate limited for '51'. Waiting 20 seconds...
Rate limited for '51'. Waiting 30 seconds...
Search skipped after retries: 51
Collected unique players: 148
[22/2000] Searching term: 5755
Collected unique players: 148
[23/2000] Searching term: gdzv
Collected unique players: 148
[24/2000] Searching term: t5j
Collected unique players: 148
[25/2000] Searching term: 82b
Collected unique players: 153
[26/2000] Searching term: gstf
Collected unique players: 153
[27/2000] Searching term: llig
Collected unique players: 156
[28/2000] Searching term: nhhf
Collected unique players: 156
[29/2000] Searching term: 2aav
Collected unique players: 156
[30/2000] Searching term: vp
Collected unique players: 176
[31/2000] Searching term: icd
Collected unique players: 186
[32/2000] Searching term: 1s
Collected unique players: 206
[33/2000] Searching term: mgc
Collected unique players: 213
[34/2000] Searching term: 7ri0
Collected unique players: 213
[35/2000] Searching term: 3pe
Collected unique players: 224
[36/2000] Searching term: rvr
Collected unique players: 242
[37/2000] Searching term: 215
Collected unique players: 253
[38/2000] Searching term: 94j
Collected unique players: 263
[39/2000] Searching term: 7ppe
Collected unique players: 263
[40/2000] Searching term: 470
Collected unique players: 268
[41/2000] Searching term: 07
Collected unique players: 288
[42/2000] Searching term: fp
Rate limited for 'fp'. Waiting 10 seconds...
Rate limited for 'fp'. Waiting 20 seconds...
Rate limited for 'fp'. Waiting 30 seconds...
Search skipped after retries: fp
Collected unique players: 288
[43/2000] Searching term: xi
Collected unique players: 308
[44/2000] Searching term: gs8w
Collected unique players: 308
[45/2000] Searching term: 5ke
Collected unique players: 325
[46/2000] Searching term: huh
Collected unique players: 345
[47/2000] Searching term: fr
Search failed for query 'fr': HTTPSConnectionPool(host='api.wiseoldman.net', port=443): Read timed out. (read timeout=15)
Collected unique players: 345
[48/2000] Searching term: 0y2e
Collected unique players: 345
[49/2000] Searching term: 1q
Collected unique players: 365
[50/2000] Searching term: c1uq
Collected unique players: 365
[51/2000] Searching term: wji
Collected unique players: 367
[52/2000] Searching term: 8sll
Collected unique players: 367
[53/2000] Searching term: 73
Collected unique players: 387
[54/2000] Searching term: w5
Collected unique players: 407
[55/2000] Searching term: 1k2w
Collected unique players: 407
[56/2000] Searching term: nhp1
Collected unique players: 407
[57/2000] Searching term: aeyv
Collected unique players: 407
[58/2000] Searching term: hzxg
Collected unique players: 407
[59/2000] Searching term: 99b
Collected unique players: 427
[60/2000] Searching term: a7g
Collected unique players: 431
[61/2000] Searching term: y7u
Collected unique players: 431
[62/2000] Searching term: pp
Collected unique players: 451
[63/2000] Searching term: vv
Rate limited for 'vv'. Waiting 10 seconds...
Rate limited for 'vv'. Waiting 20 seconds...
Collected unique players: 471
[64/2000] Searching term: cn
Collected unique players: 491
[65/2000] Searching term: ci5
Collected unique players: 491
[66/2000] Searching term: 9eo
Collected unique players: 491
[67/2000] Searching term: 1ejb
Collected unique players: 491
[68/2000] Searching term: di7n
Collected unique players: 491
[69/2000] Searching term: gp
Collected unique players: 511
[70/2000] Searching term: if
Collected unique players: 531
[71/2000] Searching term: cw
Collected unique players: 551
[72/2000] Searching term: u6y
Collected unique players: 551
[73/2000] Searching term: qt
Collected unique players: 571
[74/2000] Searching term: 1li
Collected unique players: 591
[75/2000] Searching term: jcju
Collected unique players: 592
[76/2000] Searching term: 1a78
Collected unique players: 592
[77/2000] Searching term: 03
Collected unique players: 612
[78/2000] Searching term: wdzr
Collected unique players: 612
[79/2000] Searching term: 8669
Collected unique players: 612
[80/2000] Searching term: i0u2
Collected unique players: 613
[81/2000] Searching term: ecew
Collected unique players: 613
[82/2000] Searching term: ha
Collected unique players: 633
[83/2000] Searching term: yws
Rate limited for 'yws'. Waiting 10 seconds...
Rate limited for 'yws'. Waiting 20 seconds...
Rate limited for 'yws'. Waiting 30 seconds...
Search skipped after retries: yws
Collected unique players: 633
[84/2000] Searching term: yh9
Collected unique players: 633
[85/2000] Searching term: qd
Collected unique players: 653
[86/2000] Searching term: tkz
Collected unique players: 657
[87/2000] Searching term: gi0d
Collected unique players: 657
[88/2000] Searching term: gw3
Collected unique players: 659
[89/2000] Searching term: gvbs
Collected unique players: 659
[90/2000] Searching term: xe6v
Collected unique players: 659
[91/2000] Searching term: 7tuj
Collected unique players: 659
[92/2000] Searching term: 20q
Collected unique players: 663
[93/2000] Searching term: d7mx
Collected unique players: 663
[94/2000] Searching term: ksw
Collected unique players: 675
[95/2000] Searching term: 8d7m
Collected unique players: 675
[96/2000] Searching term: 5x7
Collected unique players: 676
[97/2000] Searching term: qwb0
Collected unique players: 676
[98/2000] Searching term: 3eh5
Collected unique players: 676
[99/2000] Searching term: 7923
Collected unique players: 676
[100/2000] Searching term: oe3
Collected unique players: 676
[101/2000] Searching term: aef9
Collected unique players: 676
[102/2000] Searching term: p1nj
Collected unique players: 676
[103/2000] Searching term: 1ye2
Collected unique players: 676
[104/2000] Searching term: d6xd
Rate limited for 'd6xd'. Waiting 10 seconds...
Rate limited for 'd6xd'. Waiting 20 seconds...
Rate limited for 'd6xd'. Waiting 30 seconds...
Search skipped after retries: d6xd
Collected unique players: 676
[105/2000] Searching term: 6ky9
Collected unique players: 676
[106/2000] Searching term: g2v
Collected unique players: 676
[107/2000] Searching term: 5sz9
Collected unique players: 676
[108/2000] Searching term: v77g
Collected unique players: 676
[109/2000] Searching term: b2p
Collected unique players: 685
[110/2000] Searching term: tqd4
Collected unique players: 685
[111/2000] Searching term: prz
Collected unique players: 705
[112/2000] Searching term: zoi
Collected unique players: 725
[113/2000] Searching term: 9u9
Collected unique players: 726
[114/2000] Searching term: 9u
Collected unique players: 745
[115/2000] Searching term: a654
Collected unique players: 745
[116/2000] Searching term: 3cv
Collected unique players: 745
[117/2000] Searching term: qdt
Collected unique players: 746
[118/2000] Searching term: qj7
Collected unique players: 746
[119/2000] Searching term: 84w
Collected unique players: 748
[120/2000] Searching term: hj
Collected unique players: 768
[121/2000] Searching term: q7
Collected unique players: 778
[122/2000] Searching term: o6o
Collected unique players: 780

[123/2000] Searching term: s601
Collected unique players: 780
[124/2000] Searching term: g1i
Collected unique players: 791
[125/2000] Searching term: lnl
Rate limited for 'lnl'. Waiting 10 seconds...
Rate limited for 'lnl'. Waiting 20 seconds...
Rate limited for 'lnl'. Waiting 30 seconds...
Search skipped after retries: lnl
Collected unique players: 791
[126/2000] Searching term: ww5
Collected unique players: 791
[127/2000] Searching term: i9l
Collected unique players: 792
[128/2000] Searching term: iv4
Collected unique players: 797
[129/2000] Searching term: xs
Collected unique players: 817
[130/2000] Searching term: w48
Collected unique players: 823
[131/2000] Searching term: nb
Collected unique players: 843
[132/2000] Searching term: vy
Collected unique players: 863
[133/2000] Searching term: 9yv
Collected unique players: 863
[134/2000] Searching term: xx9
Collected unique players: 874
[135/2000] Searching term: c2q
Collected unique players: 875
[136/2000] Searching term: nz
Collected unique players: 895
[137/2000] Searching term: 852f
Collected unique players: 895
[138/2000] Searching term: 8u2
Collected unique players: 896
[139/2000] Searching term: p6eg
Collected unique players: 896
[140/2000] Searching term: ytgn
Collected unique players: 896
[141/2000] Searching term: w9n
Collected unique players: 896
[142/2000] Searching term: t0vx
Collected unique players: 896
[143/2000] Searching term: ojrj
Collected unique players: 896
[144/2000] Searching term: udd4
Collected unique players: 896
[145/2000] Searching term: tx1m
Collected unique players: 896
[146/2000] Searching term: jqh
Rate limited for 'jqh'. Waiting 10 seconds...
Rate limited for 'jqh'. Waiting 20 seconds...
Rate limited for 'jqh'. Waiting 30 seconds...
Search skipped after retries: jqh
Collected unique players: 896
[147/2000] Searching term: cmkr
Collected unique players: 898
[148/2000] Searching term: klx
Collected unique players: 901
[149/2000] Searching term: qy
Collected unique players: 921
[150/2000] Searching term: nu0
Collected unique players: 925
[151/2000] Searching term: n4yt
Collected unique players: 925
[152/2000] Searching term: 03v
Collected unique players: 926
[153/2000] Searching term: sqmc
Collected unique players: 926
[154/2000] Searching term: 2x
Collected unique players: 946
[155/2000] Searching term: pg4
Collected unique players: 947
[156/2000] Searching term: 9ndl
Collected unique players: 947
[157/2000] Searching term: fuya
Collected unique players: 949
[158/2000] Searching term: uqke
Collected unique players: 949
[159/2000] Searching term: 23sy
Collected unique players: 949
[160/2000] Searching term: j4
Collected unique players: 969
[161/2000] Searching term: rf
Collected unique players: 989
[162/2000] Searching term: p3y
Collected unique players: 990
[163/2000] Searching term: kds
Collected unique players: 1001

(1000,
 ['Obbyy',
  'Obby Cape',
  'Obby Apples',
  'Obby Kenobi',
  'obbE x',
  'Obby200',
  'Obby z',
  'obby',
  'obbiz',
  'Obby wang',
  'obbenheimer',
  'Obbib',
  'obbie bobbie',
  'Obbbo',
  'Obby Jonatan',
  'ObbMan',
  'Obby Skid',
  'obby chkn',
  'ObbyLobster',
  'obbset'])

## 8. Save collected player names

The collected usernames are saved separately.

This makes the data collection process more reproducible and allows reusing the same player list later.

In [22]:
player_names_path = PROCESSED_DATA_DIR / "osrs_collected_player_names.csv"

pd.DataFrame({"player": player_names}).to_csv(
    player_names_path,
    index=False,
    encoding="utf-8"
)

player_names_path

WindowsPath('C:/Projects/osrs-player-segmentation/data/processed/osrs_collected_player_names.csv')

## 9. Define OSRS Hiscores skill structure

The OSRS Hiscores endpoint returns skill data in a fixed order.

Each skill row contains:

- rank,
- level,
- experience.

The skill list must match the order returned by the Hiscores endpoint.

In [23]:
SKILLS = [
    "overall",
    "attack",
    "defence",
    "strength",
    "hitpoints",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecraft",
    "hunter",
    "construction",
    "sailing"
]

## Define OSRS boss Hiscores structure

After the skill section, the Hiscores response contains activity and boss killcount rows.

Boss rows usually contain:

- rank,
- killcount.

In [32]:
BOSSES = [
    "abyssal_sire",
    "alchemical_hydra",
    "barrows_chests",
    "bryophyta",
    "callisto",
    "cerberus",
    "chambers_of_xeric",
    "chambers_of_xeric_challenge_mode",
    "chaos_elemental",
    "chaos_fanatic",
    "commander_zilyana",
    "corporeal_beast",
    "crazy_archaeologist",
    "dagannoth_prime",
    "dagannoth_rex",
    "dagannoth_supreme",
    "deranged_archaeologist",
    "general_graardor",
    "giant_mole",
    "grotesque_guardians",
    "hespori",
    "kalphite_queen",
    "king_black_dragon",
    "kraken",
    "kreearra",
    "kril_tsutsaroth",
    "mimic",
    "nightmare",
    "obor",
    "sarachnis",
    "scorpia",
    "skotizo",
    "the_gauntlet",
    "the_corrupted_gauntlet",
    "theatre_of_blood",
    "thermonuclear_smoke_devil",
    "tzkal_zuk",
    "tztok_jad",
    "venenatis",
    "vetion",
    "vorkath",
    "wintertodt",
    "zalcano",
    "zulrah"
]

## 10. Fetch OSRS Hiscores data

After collecting player names, this section downloads public OSRS Hiscores data for each player.

In [54]:
from urllib.parse import quote

def fetch_wom_player_details(player_name, max_retries=2):
    """
    Fetch player details from Wise Old Man API.
    Handles spaces/special characters and basic retry logic.
    """
    encoded_name = quote(player_name, safe="")
    url = f"https://api.wiseoldman.net/v2/players/{encoded_name}"

    headers = {
        "User-Agent": "osrs-player-segmentation-student-project/1.0"
    }

    for attempt in range(max_retries):
        try:
            response = requests.get(url, headers=headers, timeout=15)

            if response.status_code == 200:
                return response.json()

            if response.status_code in [403, 429]:
                wait_time = 5 * (attempt + 1)
                print(f"Rate/permission issue for {player_name} ({response.status_code}). Waiting {wait_time}s...")
                time.sleep(wait_time)
                continue

            print(f"Failed: {player_name} - HTTP {response.status_code}")
            return None

        except requests.RequestException as error:
            print(f"Request error for {player_name}: {error}")
            return None

    print(f"Skipped after retries: {player_name}")
    return None

## 11. Parse Hiscores data

The raw Hiscores response is text-based.

This function converts the skill section into a structured Python dictionary.

In [55]:
def parse_wom_player_details(player_name, data):
    """
    Parse Wise Old Man PlayerDetails JSON into a flat row.

    The latestSnapshot object contains skills, bosses and activities.
    """
    player_data = {
        "player": player_name
    }

    latest_snapshot = data.get("latestSnapshot")

    if not latest_snapshot:
        return player_data

    data_block = latest_snapshot.get("data", {})

    for category_name in ["skills", "bosses", "activities"]:
        category = data_block.get(category_name, {})

        for metric_name, metric_values in category.items():
            prefix = metric_name.lower()

            if category_name == "skills":
                player_data[f"{prefix}_rank"] = metric_values.get("rank")
                player_data[f"{prefix}_level"] = metric_values.get("level")
                player_data[f"{prefix}_xp"] = metric_values.get("experience")

            elif category_name == "bosses":
                player_data[f"{prefix}_rank"] = metric_values.get("rank")
                player_data[f"{prefix}_kc"] = metric_values.get("kills")

            elif category_name == "activities":
                player_data[f"{prefix}_rank"] = metric_values.get("rank")
                player_data[f"{prefix}_score"] = metric_values.get("score")

    return player_data

## 12. Download Hiscores data for collected players

This step iterates through the collected player list and downloads Hiscores data for each player.

Invalid or unavailable player profiles are skipped.

In [56]:
records = []
failed_players = []

for index, player_name in enumerate(player_names, start=1):
    print(f"[{index}/{len(player_names)}] Fetching WOM details: {player_name}")

    data = fetch_wom_player_details(player_name)

    if data is None:
        failed_players.append(player_name)
        continue

    parsed_data = parse_wom_player_details(player_name, data)
    records.append(parsed_data)

    time.sleep(0.5)

df_hiscores = pd.DataFrame(records)

df_hiscores.head()

[1/1000] Fetching WOM details: Obbyy
[2/1000] Fetching WOM details: Obby Cape
[3/1000] Fetching WOM details: Obby Apples
[4/1000] Fetching WOM details: Obby Kenobi
[5/1000] Fetching WOM details: obbE x
[6/1000] Fetching WOM details: Obby200
[7/1000] Fetching WOM details: Obby z
[8/1000] Fetching WOM details: obby
[9/1000] Fetching WOM details: obbiz
[10/1000] Fetching WOM details: Obby wang
[11/1000] Fetching WOM details: obbenheimer
[12/1000] Fetching WOM details: Obbib
[13/1000] Fetching WOM details: obbie bobbie
[14/1000] Fetching WOM details: Obbbo
[15/1000] Fetching WOM details: Obby Jonatan
[16/1000] Fetching WOM details: ObbMan
[17/1000] Fetching WOM details: Obby Skid
[18/1000] Fetching WOM details: obby chkn
Rate/permission issue for obby chkn (429). Waiting 5s...
Rate/permission issue for obby chkn (429). Waiting 10s...
Skipped after retries: obby chkn
[19/1000] Fetching WOM details: ObbyLobster
Rate/permission issue for ObbyLobster (429). Waiting 5s...
[20/1000] Fetching WOM details: obbset
[21/1000] Fetching WOM details: XpolakX
[22/1000] Fetching WOM details: xPolyphia
[23/1000] Fetching WOM details: xPodd
[24/1000] Fetching WOM details: XPOQ
[25/1000] Fetching WOM details: xpopx
[26/1000] Fetching WOM details: XPop
[27/1000] Fetching WOM details: xpozure
[28/1000] Fetching WOM details: xpoods
[29/1000] Fetching WOM details: xPool xCue
[30/1000] Fetching WOM details: xpowerx4040
[31/1000] Fetching WOM details: xPoliwag
[32/1000] Fetching WOM details: xpolarr
[33/1000] Fetching WOM details: xpoltergiest
[34/1000] Fetching WOM details: xportgas
[35/1000] Fetching WOM details: xpopsicles
[36/1000] Fetching WOM details: xPolo
[37/1000] Fetching WOM details: XpOverBooze
[38/1000] Fetching WOM details: xpol
[39/1000] Fetching WOM details: xPottz
Rate/permission issue for xPottz (429). Waiting 5s...
Rate/permission issue for xPottz (429). Waiting 10s...
Skipped after retries: xPottz
[40/1000] Fetching WOM details: xpotatoex
Rate/permission issue for xpotatoex (429). Waiting 5s...
Rate/permission issue for xpotatoex (429). Waiting 10s...
Skipped after retries: xpotatoex
[41/1000] Fetching WOM details: i42O
Rate/permission issue for i42O (429). Waiting 5s...
Rate/permission issue for i42O (429). Waiting 10s...
Skipped after retries: i42O
[42/1000] Fetching WOM details: i420sm0ke
Rate/permission issue for i420sm0ke (429). Waiting 5s...
[43/1000] Fetching WOM details: i42
[44/1000] Fetching WOM details: i420u
[45/1000] Fetching WOM details: i420on911
[46/1000] Fetching WOM details: i42p
[47/1000] Fetching WOM details: I420x69I
[48/1000] Fetching WOM details: i42D
[49/1000] Fetching WOM details: i42i
[50/1000] Fetching WOM details: wsv
[51/1000] Fetching WOM details: wsop
[52/1000] Fetching WOM details: WS6
[53/1000] Fetching WOM details: wsft
[54/1000] Fetching WOM details: wstd penguin
[55/1000] Fetching WOM details: wsvolt
[56/1000] Fetching WOM details: WSPanicFan
[57/1000] Fetching WOM details: wSquallw
[58/1000] Fetching WOM details: wsf
[59/1000] Fetching WOM details: Wsun8
[60/1000] Fetching WOM details: wsj
[61/1000] Fetching WOM details: WsixtyFive
[62/1000] Fetching WOM details: ws daplug
Rate/permission issue for ws daplug (429). Waiting 5s...
Rate/permission issue for ws daplug (429). Waiting 10s...
Skipped after retries: ws daplug
[63/1000] Fetching WOM details: WS ZaIc
Rate/permission issue for WS ZaIc (429). Waiting 5s...
Rate/permission issue for WS ZaIc (429). Waiting 10s...
Skipped after retries: WS ZaIc
[64/1000] Fetching WOM details: WSedanOwner
Rate/permission issue for WSedanOwner (429). Waiting 5s...
Rate/permission issue for WSedanOwner (429). Waiting 10s...
Skipped after retries: WSedanOwner
[65/1000] Fetching WOM details: wsmdavey
Rate/permission issue for wsmdavey (429). Waiting 5s...
[66/1000] Fetching WOM details: Wsupden
[67/1000] Fetching WOM details: WsInDaSchat
[68/1000] Fetching WOM details: WS4L
[69/1000] Fetching WOM details: ws jr
[70/1000] Fetching WOM details: dmp v3
[71/1000] Fetching WOM details: DMM Limey
[72/1000] Fetching WOM details: Dmuu
[73/1000] Fetching WOM details: DMT
[74/1000] Fetching WOM details: DM Allstars
[75/1000] Fetching WOM details: Dmeaand
[76/1000] Fetching WOM details: Dmpm
[77/1000] Fetching WOM details: DMMTest0002
[78/1000] Fetching WOM details: Dm8
[79/1000] Fetching WOM details: dman0o
[80/1000] Fetching WOM details: dmitri333
[81/1000] Fetching WOM details: Dmt n Thc
[82/1000] Fetching WOM details: DMM Rak
[83/1000] Fetching WOM details: DM26
[84/1000] Fetching WOM details: DM ME 4 KITS
[85/1000] Fetching WOM details: dmoz
Rate/permission issue for dmoz (429). Waiting 5s...
Rate/permission issue for dmoz (429). Waiting 10s...
Skipped after retries: dmoz
[86/1000] Fetching WOM details: dm 4 pawjob
Rate/permission issue for dm 4 pawjob (429). Waiting 5s...
Rate/permission issue for dm 4 pawjob (429). Waiting 10s...
Skipped after retries: dm 4 pawjob
[87/1000] Fetching WOM details: dmb
Rate/permission issue for dmb (429). Waiting 5s...
Rate/permission issue for dmb (429). Waiting 10s...
Skipped after retries: dmb
[88/1000] Fetching WOM details: Dmer btw
Rate/permission issue for Dmer btw (429). Waiting 5s...
[89/1000] Fetching WOM details: Dmhc
[90/1000] Fetching WOM details: 7f7U7C7K7Y7U
[91/1000] Fetching WOM details: W1ddy
[92/1000] Fetching WOM details: W1D
[93/1000] Fetching WOM details: w1dowmakerx
[94/1000] Fetching WOM details: W1DE OPEN
[95/1000] Fetching WOM details: w1de
[96/1000] Fetching WOM details: W1D0WG1rl
[97/1000] Fetching WOM details: w1dowmaker
[98/1000] Fetching WOM details: W1d3h4rd
[99/1000] Fetching WOM details: tbzycutie
[100/1000] Fetching WOM details: TBZ
[101/1000] Fetching WOM details: Tbztom
[102/1000] Fetching WOM details: Tbzgamer23
[103/1000] Fetching WOM details: tbzRS
[104/1000] Fetching WOM details: tbzsd
[105/1000] Fetching WOM details: tbz12
[106/1000] Fetching WOM details: Tbzgamer2341
[107/1000] Fetching WOM details: Tbzgamer
[108/1000] Fetching WOM details: n6s8tb2an7p
Rate/permission issue for n6s8tb2an7p (429). Waiting 5s...
Rate/permission issue for n6s8tb2an7p (429). Waiting 10s...
Skipped after retries: n6s8tb2an7p
[109/1000] Fetching WOM details: 0rthru5
Rate/permission issue for 0rthru5 (429). Waiting 5s...
Rate/permission issue for 0rthru5 (429). Waiting 10s...
Skipped after retries: 0rthru5
[110/1000] Fetching WOM details: 0regy
Rate/permission issue for 0regy (429). Waiting 5s...
Rate/permission issue for 0regy (429). Waiting 10s...
Skipped after retries: 0regy
[111/1000] Fetching WOM details: 0rtistic
Rate/permission issue for 0rtistic (429). Waiting 5s...
[112/1000] Fetching WOM details: 0riole
[113/1000] Fetching WOM details: 0rochibi
[114/1000] Fetching WOM details: 0RNGxMiQi
[115/1000] Fetching WOM details: 0rzhov
[116/1000] Fetching WOM details: 0rsoNosr0
[117/1000] Fetching WOM details: 0Ryan
[118/1000] Fetching WOM details: 0ry
[119/1000] Fetching WOM details: 0REFANS
[120/1000] Fetching WOM details: 0rton7
[121/1000] Fetching WOM details: 0rnstein
[122/1000] Fetching WOM details: 0rganic
[123/1000] Fetching WOM details: 0regon Ducks
[124/1000] Fetching WOM details: 0rdi
[125/1000] Fetching WOM details: 0re0slayer
[126/1000] Fetching WOM details: 0rangeSpice
[127/1000] Fetching WOM details: 0raf
[128/1000] Fetching WOM details: 0rkney
[129/1000] Fetching WOM details: nvrspoon
[130/1000] Fetching WOM details: NvrDie420
[131/1000] Fetching WOM details: NVREVRLUCKY
Rate/permission issue for NVREVRLUCKY (429). Waiting 5s...
Rate/permission issue for NVREVRLUCKY (429). Waiting 10s...
Skipped after retries: NVREVRLUCKY
[132/1000] Fetching WOM details: nvrsang
Rate/permission issue for nvrsang (429). Waiting 5s...
Rate/permission issue for nvrsang (429). Waiting 10s...
Skipped after retries: nvrsang
[133/1000] Fetching WOM details: nvda go up
Rate/permission issue for nvda go up (429). Waiting 5s...
Rate/permission issue for nvda go up (429). Waiting 10s...
Skipped after retries: nvda go up
[134/1000] Fetching WOM details: Nvr Ironman
Rate/permission issue for Nvr Ironman (429). Waiting 5s...
[135/1000] Fetching WOM details: Nvrforget
[136/1000] Fetching WOM details: nvs
[137/1000] Fetching WOM details: NvrMaxLivin
[138/1000] Fetching WOM details: NVQ

[139/1000] Fetching WOM details: NvMe
[140/1000] Fetching WOM details: nvrpuloutevr
[141/1000] Fetching WOM details: nvlI
[142/1000] Fetching WOM details: NVNV
[143/1000] Fetching WOM details: Nvsh
[144/1000] Fetching WOM details: NvMy Madness
[145/1000] Fetching WOM details: Nvious7
[146/1000] Fetching WOM details: Nvision
[147/1000] Fetching WOM details: nvrpurplight
[148/1000] Fetching WOM details: nvm ur tits
[149/1000] Fetching WOM details: 82bangbang
[150/1000] Fetching WOM details: 82busyair
[151/1000] Fetching WOM details: 82borkloki
[152/1000] Fetching WOM details: 82balduract
[153/1000] Fetching WOM details: 82bringthor
[154/1000] Fetching WOM details: lligmah
Rate/permission issue for lligmah (429). Waiting 5s...
Rate/permission issue for lligmah (429). Waiting 10s...
Skipped after retries: lligmah
[155/1000] Fetching WOM details: LLIGMA
Rate/permission issue for LLIGMA (429). Waiting 5s...
Rate/permission issue for LLIGMA (429). Waiting 10s...
Skipped after retries: LLIGMA
[156/1000] Fetching WOM details: lligetlucky
Rate/permission issue for lligetlucky (429). Waiting 5s...
Rate/permission issue for lligetlucky (429). Waiting 10s...
Skipped after retries: lligetlucky
[157/1000] Fetching WOM details: vpt
Rate/permission issue for vpt (429). Waiting 5s...
[158/1000] Fetching WOM details: Vpadz
[159/1000] Fetching WOM details: vpn
[160/1000] Fetching WOM details: vper
[161/1000] Fetching WOM details: VPurpleK
[162/1000] Fetching WOM details: VpV
[163/1000] Fetching WOM details: vp9sk
[164/1000] Fetching WOM details: Vpsxsam
[165/1000] Fetching WOM details: VP Bam
[166/1000] Fetching WOM details: VPSR
[167/1000] Fetching WOM details: Vpat
[168/1000] Fetching WOM details: VPIIPER
[169/1000] Fetching WOM details: vpked
[170/1000] Fetching WOM details: VP IronChef
[171/1000] Fetching WOM details: vPaperMario
[172/1000] Fetching WOM details: VPN Advert
[173/1000] Fetching WOM details: Vp3
[174/1000] Fetching WOM details: VP N1ck
[175/1000] Fetching WOM details: VPX
[176/1000] Fetching WOM details: vp kj
[177/1000] Fetching WOM details: ICDAS
Rate/permission issue for ICDAS (429). Waiting 5s...
Rate/permission issue for ICDAS (429). Waiting 10s...
Skipped after retries: ICDAS
[178/1000] Fetching WOM details: ICDD
Rate/permission issue for ICDD (429). Waiting 5s...
Rate/permission issue for ICDD (429). Waiting 10s...
Skipped after retries: ICDD
[179/1000] Fetching WOM details: ICDeadPixels
Rate/permission issue for ICDeadPixels (429). Waiting 5s...
Rate/permission issue for ICDeadPixels (429). Waiting 10s...
Skipped after retries: ICDeadPixels
[180/1000] Fetching WOM details: icdh
Rate/permission issue for icdh (429). Waiting 5s...
[181/1000] Fetching WOM details: IcdeadIron
[182/1000] Fetching WOM details: ICD 10F84
[183/1000] Fetching WOM details: ICDEADPE0PLE
[184/1000] Fetching WOM details: icd 10
[185/1000] Fetching WOM details: icdeadppl21
[186/1000] Fetching WOM details: icd tea
[187/1000] Fetching WOM details: 1st ed mint
[188/1000] Fetching WOM details: 1st son
[189/1000] Fetching WOM details: 1s True Love
[190/1000] Fetching WOM details: 1st Civ Div
[191/1000] Fetching WOM details: 1stSentinel
[192/1000] Fetching WOM details: 1st in space
[193/1000] Fetching WOM details: 1Stunner ISU
[194/1000] Fetching WOM details: 1Swan
[195/1000] Fetching WOM details: 1s1am
[196/1000] Fetching WOM details: 1st ironman
[197/1000] Fetching WOM details: 1sersje1
[198/1000] Fetching WOM details: 1scrim
[199/1000] Fetching WOM details: 1SkilledMofo
[200/1000] Fetching WOM details: 1sema
Rate/permission issue for 1sema (429). Waiting 5s...
Rate/permission issue for 1sema (429). Waiting 10s...
Skipped after retries: 1sema
[201/1000] Fetching WOM details: 1st billiam
Rate/permission issue for 1st billiam (429). Waiting 5s...
Rate/permission issue for 1st billiam (429). Waiting 10s...
Skipped after retries: 1st billiam
[202/1000] Fetching WOM details: 1swampdonkey
Rate/permission issue for 1swampdonkey (429). Waiting 5s...
Rate/permission issue for 1swampdonkey (429). Waiting 10s...
Skipped after retries: 1swampdonkey
[203/1000] Fetching WOM details: 1starkiller2
Rate/permission issue for 1starkiller2 (429). Waiting 5s...
[204/1000] Fetching WOM details: 1snow234
[205/1000] Fetching WOM details: 1st Sorcerer
[206/1000] Fetching WOM details: 1st trav
[207/1000] Fetching WOM details: mgcmushroom
[208/1000] Fetching WOM details: mgcsmokeshop
[209/1000] Fetching WOM details: mgCiN
[210/1000] Fetching WOM details: mgChomp
[211/1000] Fetching WOM details: mgc zanthire
[212/1000] Fetching WOM details: mgcpure4boyz
[213/1000] Fetching WOM details: mgc
[214/1000] Fetching WOM details: 3Persons1God
[215/1000] Fetching WOM details: 3pendragon
[216/1000] Fetching WOM details: 3persons
[217/1000] Fetching WOM details: 3PetViking
[218/1000] Fetching WOM details: 3peiceNsoda
[219/1000] Fetching WOM details: 3peezy
[220/1000] Fetching WOM details: 3pet no seed
[221/1000] Fetching WOM details: 3Peat
[222/1000] Fetching WOM details: 3pence
[223/1000] Fetching WOM details: 3peterson
Rate/permission issue for 3peterson (429). Waiting 5s...
Rate/permission issue for 3peterson (429). Waiting 10s...
Skipped after retries: 3peterson
[224/1000] Fetching WOM details: 3PetsNoDrop
Rate/permission issue for 3PetsNoDrop (429). Waiting 5s...
Rate/permission issue for 3PetsNoDrop (429). Waiting 10s...
Skipped after retries: 3PetsNoDrop
[225/1000] Fetching WOM details: rvrsa
Rate/permission issue for rvrsa (429). Waiting 5s...
Rate/permission issue for rvrsa (429). Waiting 10s...
Skipped after retries: rvrsa
[226/1000] Fetching WOM details: rvre
Rate/permission issue for rvre (429). Waiting 5s...
[227/1000] Fetching WOM details: RvR777
[228/1000] Fetching WOM details: Rvrsegiraffe
[229/1000] Fetching WOM details: rvrt
[230/1000] Fetching WOM details: rvrie
[231/1000] Fetching WOM details: RVrsso
[232/1000] Fetching WOM details: Rvrman15
[233/1000] Fetching WOM details: rvrso
[234/1000] Fetching WOM details: rvrsbass
[235/1000] Fetching WOM details: rvr bear1
[236/1000] Fetching WOM details: rvry
[237/1000] Fetching WOM details: RVRE GHVST
[238/1000] Fetching WOM details: rvrse7
[239/1000] Fetching WOM details: rvrcitysaint
[240/1000] Fetching WOM details: rvre king
[241/1000] Fetching WOM details: RVRRVRVVRV
[242/1000] Fetching WOM details: Rvrman13
[243/1000] Fetching WOM details: 2158SORROWWA
[244/1000] Fetching WOM details: 2155
[245/1000] Fetching WOM details: 2152323
[246/1000] Fetching WOM details: 215ms
Rate/permission issue for 215ms (429). Waiting 5s...
Rate/permission issue for 215ms (429). Waiting 10s...
Skipped after retries: 215ms
[247/1000] Fetching WOM details: 215lbs
Rate/permission issue for 215lbs (429). Waiting 5s...
Rate/permission issue for 215lbs (429). Waiting 10s...
Skipped after retries: 215lbs
[248/1000] Fetching WOM details: 215lb cake
Rate/permission issue for 215lb cake (429). Waiting 5s...
Rate/permission issue for 215lb cake (429). Waiting 10s...
Skipped after retries: 215lb cake
[249/1000] Fetching WOM details: 21521
Rate/permission issue for 21521 (429). Waiting 5s...
[250/1000] Fetching WOM details: 215214213
[251/1000] Fetching WOM details: 215 Go Birds
[252/1000] Fetching WOM details: 2152
[253/1000] Fetching WOM details: 215
[254/1000] Fetching WOM details: 94JG
[255/1000] Fetching WOM details: 94JW
[256/1000] Fetching WOM details: 94just94
[257/1000] Fetching WOM details: 94jdr2
[258/1000] Fetching WOM details: 94jadefate
[259/1000] Fetching WOM details: 94JGym
[260/1000] Fetching WOM details: 94JGim
[261/1000] Fetching WOM details: 94judgearm
[262/1000] Fetching WOM details: 94JH
[263/1000] Fetching WOM details: 94judge2180
[264/1000] Fetching WOM details: 47000
[265/1000] Fetching WOM details: 4701
[266/1000] Fetching WOM details: 470k
[267/1000] Fetching WOM details: 470tfmbnku3
[268/1000] Fetching WOM details: 4702
[269/1000] Fetching WOM details: 07 iron
Rate/permission issue for 07 iron (429). Waiting 5s...
Rate/permission issue for 07 iron (429). Waiting 10s...
Skipped after retries: 07 iron
[270/1000] Fetching WOM details: 07dive
Rate/permission issue for 07dive (429). Waiting 5s...
Rate/permission issue for 07dive (429). Waiting 10s...

Skipped after retries: 07dive
[271/1000] Fetching WOM details: 07 Flare
Rate/permission issue for 07 Flare (429). Waiting 5s...
Rate/permission issue for 07 Flare (429). Waiting 10s...
Skipped after retries: 07 Flare
[272/1000] Fetching WOM details: 07 Nihilist
Rate/permission issue for 07 Nihilist (429). Waiting 5s...
[273/1000] Fetching WOM details: 07 Hollyman
[274/1000] Fetching WOM details: 07Mana
[275/1000] Fetching WOM details: 07Ashley
[276/1000] Fetching WOM details: 07wan
[277/1000] Fetching WOM details: 07Chris
[278/1000] Fetching WOM details: 07 0
[279/1000] Fetching WOM details: 07 Preacher
[280/1000] Fetching WOM details: 07 tim
[281/1000] Fetching WOM details: 07 PRISMA
[282/1000] Fetching WOM details: 07 t bone
[283/1000] Fetching WOM details: 07Geno
[284/1000] Fetching WOM details: 07TroyScape
[285/1000] Fetching WOM details: 07 maisy
[286/1000] Fetching WOM details: 07 ezra
[287/1000] Fetching WOM details: 07 Account
[288/1000] Fetching WOM details: 07 Camry
[289/1000] Fetching WOM details: Ximu
[290/1000] Fetching WOM details: Xijaxer
[291/1000] Fetching WOM details: xiao wei
[292/1000] Fetching WOM details: Xill
Rate/permission issue for Xill (429). Waiting 5s...
Rate/permission issue for Xill (429). Waiting 10s...
Skipped after retries: Xill
[293/1000] Fetching WOM details: Xiny
Rate/permission issue for Xiny (429). Waiting 5s...
Rate/permission issue for Xiny (429). Waiting 10s...
Skipped after retries: Xiny
[294/1000] Fetching WOM details: xi li er
Rate/permission issue for xi li er (429). Waiting 5s...
Rate/permission issue for xi li er (429). Waiting 10s...
Skipped after retries: xi li er
[295/1000] Fetching WOM details: Xiuol
Rate/permission issue for Xiuol (429). Waiting 5s...
[296/1000] Fetching WOM details: xinara
[297/1000] Fetching WOM details: XiTe VKG
[298/1000] Fetching WOM details: Xinram
[299/1000] Fetching WOM details: Xiley
[300/1000] Fetching WOM details: XI5
[301/1000] Fetching WOM details: xiamo
[302/1000] Fetching WOM details: XIqFpFFqEdF
[303/1000] Fetching WOM details: Xilsy
[304/1000] Fetching WOM details: XI J
[305/1000] Fetching WOM details: xIron Senpai
[306/1000] Fetching WOM details: Xiaolou
[307/1000] Fetching WOM details: xim no ironx
[308/1000] Fetching WOM details: Xifaren
[309/1000] Fetching WOM details: 5KEL
[310/1000] Fetching WOM details: 5ketti
[311/1000] Fetching WOM details: 5KeLLz
[312/1000] Fetching WOM details: 5kExpPerHour
[313/1000] Fetching WOM details: 5KEYZ
[314/1000] Fetching WOM details: 5kez
[315/1000] Fetching WOM details: 5KE
Rate/permission issue for 5KE (429). Waiting 5s...
Rate/permission issue for 5KE (429). Waiting 10s...
Skipped after retries: 5KE
[316/1000] Fetching WOM details: 5keeve
Rate/permission issue for 5keeve (429). Waiting 5s...
Rate/permission issue for 5keeve (429). Waiting 10s...
Skipped after retries: 5keeve
[317/1000] Fetching WOM details: 5kekmalxhunt
Rate/permission issue for 5kekmalxhunt (429). Waiting 5s...
Rate/permission issue for 5kekmalxhunt (429). Waiting 10s...
Skipped after retries: 5kekmalxhunt
[318/1000] Fetching WOM details: 5ketch Bot
Rate/permission issue for 5ketch Bot (429). Waiting 5s...
[319/1000] Fetching WOM details: 5keyplz
[320/1000] Fetching WOM details: 5keyzf4rmrun
[321/1000] Fetching WOM details: 5KEYZFARMR4N
[322/1000] Fetching WOM details: 5keyzzz7z7z
[323/1000] Fetching WOM details: 5KEYZ7ZZZ
[324/1000] Fetching WOM details: 5key barbie
[325/1000] Fetching WOM details: 5ket
[326/1000] Fetching WOM details: Huhu
[327/1000] Fetching WOM details: Huh Wuh
[328/1000] Fetching WOM details: Huhmble
[329/1000] Fetching WOM details: Huhi
[330/1000] Fetching WOM details: Huh Panda
[331/1000] Fetching WOM details: Huh who
[332/1000] Fetching WOM details: huhsmokey
[333/1000] Fetching WOM details: Huhdunkachud
[334/1000] Fetching WOM details: huhhwhat
[335/1000] Fetching WOM details: Huhdis
[336/1000] Fetching WOM details: huh tch
[337/1000] Fetching WOM details: huh hels
[338/1000] Fetching WOM details: huhduken
Rate/permission issue for huhduken (429). Waiting 5s...
Rate/permission issue for huhduken (429). Waiting 10s...
Skipped after retries: huhduken
[339/1000] Fetching WOM details: huh yunjln
Rate/permission issue for huh yunjln (429). Waiting 5s...
Rate/permission issue for huh yunjln (429). Waiting 10s...
Skipped after retries: huh yunjln
[340/1000] Fetching WOM details: huhtasyyria
Rate/permission issue for huhtasyyria (429). Waiting 5s...
Rate/permission issue for huhtasyyria (429). Waiting 10s...
Skipped after retries: huhtasyyria
[341/1000] Fetching WOM details: huh BTW
Rate/permission issue for huh BTW (429). Waiting 5s...
[342/1000] Fetching WOM details: Huh4abiggen
[343/1000] Fetching WOM details: huhubhubadub
[344/1000] Fetching WOM details: huhbabubba24
[345/1000] Fetching WOM details: huh2
[346/1000] Fetching WOM details: 1qpunchman
[347/1000] Fetching WOM details: 1QW1bwqnGhWP
[348/1000] Fetching WOM details: 1q3513515631
[349/1000] Fetching WOM details: 1questnofarm
[350/1000] Fetching WOM details: 1qq5
[351/1000] Fetching WOM details: 1qp ironmeme
[352/1000] Fetching WOM details: 1qawsrt
[353/1000] Fetching WOM details: 1qq3
[354/1000] Fetching WOM details: 1qu3stybo1
[355/1000] Fetching WOM details: 1quest
[356/1000] Fetching WOM details: 1qo
[357/1000] Fetching WOM details: 1q156
[358/1000] Fetching WOM details: 1quickfire
[359/1000] Fetching WOM details: 1Q1 SINS
[360/1000] Fetching WOM details: 1q 84
[361/1000] Fetching WOM details: 1qaz2wsx151
Rate/permission issue for 1qaz2wsx151 (429). Waiting 5s...
Rate/permission issue for 1qaz2wsx151 (429). Waiting 10s...
Skipped after retries: 1qaz2wsx151
[362/1000] Fetching WOM details: 1qpaat
Rate/permission issue for 1qpaat (429). Waiting 5s...
Rate/permission issue for 1qpaat (429). Waiting 10s...
Skipped after retries: 1qpaat
[363/1000] Fetching WOM details: 1q c
Rate/permission issue for 1q c (429). Waiting 5s...
Rate/permission issue for 1q c (429). Waiting 10s...
Skipped after retries: 1q c
[364/1000] Fetching WOM details: 1qocWBoUtNa5
Rate/permission issue for 1qocWBoUtNa5 (429). Waiting 5s...
[365/1000] Fetching WOM details: 1Q HP
[366/1000] Fetching WOM details: wjireze629
[367/1000] Fetching WOM details: wji
[368/1000] Fetching WOM details: 734590325839
[369/1000] Fetching WOM details: 730x
[370/1000] Fetching WOM details: 737
[371/1000] Fetching WOM details: 73
[372/1000] Fetching WOM details: 73 and Kree
[373/1000] Fetching WOM details: 7314PengRS
[374/1000] Fetching WOM details: 73Funky
[375/1000] Fetching WOM details: 73 n1 gger
[376/1000] Fetching WOM details: 73Ted
[377/1000] Fetching WOM details: 73 simulator
[378/1000] Fetching WOM details: 7355608
[379/1000] Fetching WOM details: 73RP
[380/1000] Fetching WOM details: 73XD
[381/1000] Fetching WOM details: 73_or_67
[382/1000] Fetching WOM details: 73HoundKey
[383/1000] Fetching WOM details: 73 35
[384/1000] Fetching WOM details: 73oob
Rate/permission issue for 73oob (429). Waiting 5s...
Rate/permission issue for 73oob (429). Waiting 10s...
Skipped after retries: 73oob
[385/1000] Fetching WOM details: 73mas
Rate/permission issue for 73mas (429). Waiting 5s...
Rate/permission issue for 73mas (429). Waiting 10s...
Skipped after retries: 73mas
[386/1000] Fetching WOM details: 73LM
Rate/permission issue for 73LM (429). Waiting 5s...
Rate/permission issue for 73LM (429). Waiting 10s...
Skipped after retries: 73LM
[387/1000] Fetching WOM details: 73 0
Rate/permission issue for 73 0 (429). Waiting 5s...
[388/1000] Fetching WOM details: W506
[389/1000] Fetching WOM details: w533
[390/1000] Fetching WOM details: W56
[391/1000] Fetching WOM details: W5G
[392/1000] Fetching WOM details: W532ENJOYER
[393/1000] Fetching WOM details: W5
[394/1000] Fetching WOM details: w573
[395/1000] Fetching WOM details: w5apon
[396/1000] Fetching WOM details: w5s
[397/1000] Fetching WOM details: W527
[398/1000] Fetching WOM details: w511
[399/1000] Fetching WOM details: W56O
[400/1000] Fetching WOM details: w51
[401/1000] Fetching WOM details: w508
[402/1000] Fetching WOM details: w505 Mas
[403/1000] Fetching WOM details: W532
[404/1000] Fetching WOM details: W519
[405/1000] Fetching WOM details: W5O9
[406/1000] Fetching WOM details: w56 Novi

[407/1000] Fetching WOM details: w510
Rate/permission issue for w510 (429). Waiting 5s...
Rate/permission issue for w510 (429). Waiting 10s...
Skipped after retries: w510
[408/1000] Fetching WOM details: 99bottin
Rate/permission issue for 99bottin (429). Waiting 5s...
Rate/permission issue for 99bottin (429). Waiting 10s...
Skipped after retries: 99bottin
[409/1000] Fetching WOM details: 99Bank Stand
Rate/permission issue for 99Bank Stand (429). Waiting 5s...
Rate/permission issue for 99Bank Stand (429). Waiting 10s...
Skipped after retries: 99Bank Stand
[410/1000] Fetching WOM details: 99Brad
Rate/permission issue for 99Brad (429). Waiting 5s...
[411/1000] Fetching WOM details: 99bnkstnding
[412/1000] Fetching WOM details: 99botslayer
[413/1000] Fetching WOM details: 99broke
[414/1000] Fetching WOM details: 99bigworm99
[415/1000] Fetching WOM details: 99brews
[416/1000] Fetching WOM details: 99batatah
[417/1000] Fetching WOM details: 99BOXES
[418/1000] Fetching WOM details: 99b0wcap3
[419/1000] Fetching WOM details: 99bouldering
[420/1000] Fetching WOM details: 99bballfreak
[421/1000] Fetching WOM details: 99BudBlazer
[422/1000] Fetching WOM details: 99BankStandi
[423/1000] Fetching WOM details: 99boosted
[424/1000] Fetching WOM details: 99Bonds
[425/1000] Fetching WOM details: 99b4troy
[426/1000] Fetching WOM details: 99boots
[427/1000] Fetching WOM details: 99bronze2257
[428/1000] Fetching WOM details: A7geber
[429/1000] Fetching WOM details: A7G
[430/1000] Fetching WOM details: a7g6cbvz0ww
Rate/permission issue for a7g6cbvz0ww (429). Waiting 5s...
Rate/permission issue for a7g6cbvz0ww (429). Waiting 10s...
Skipped after retries: a7g6cbvz0ww
[431/1000] Fetching WOM details: A7gramblunt
Rate/permission issue for A7gramblunt (429). Waiting 5s...
Rate/permission issue for A7gramblunt (429). Waiting 10s...
Skipped after retries: A7gramblunt
[432/1000] Fetching WOM details: Ppl
Rate/permission issue for Ppl (429). Waiting 5s...
Rate/permission issue for Ppl (429). Waiting 10s...
Skipped after retries: Ppl
[433/1000] Fetching WOM details: ppppppppp
Rate/permission issue for ppppppppp (429). Waiting 5s...
[434/1000] Fetching WOM details: ppp
[435/1000] Fetching WOM details: ppirates
[436/1000] Fetching WOM details: PPeru
[437/1000] Fetching WOM details: pp23
[438/1000] Fetching WOM details: ppot
[439/1000] Fetching WOM details: Ppkrz
[440/1000] Fetching WOM details: ppprince
[441/1000] Fetching WOM details: PPMF
[442/1000] Fetching WOM details: PP Hard AF
[443/1000] Fetching WOM details: ppengu
[444/1000] Fetching WOM details: Ppenguin
[445/1000] Fetching WOM details: pp hed
[446/1000] Fetching WOM details: pp kazu
[447/1000] Fetching WOM details: PPL Split
[448/1000] Fetching WOM details: PP 3
[449/1000] Fetching WOM details: pp sneeze
[450/1000] Fetching WOM details: pp qt
[451/1000] Fetching WOM details: Pph
[452/1000] Fetching WOM details: Vvona
[453/1000] Fetching WOM details: vvtt
Rate/permission issue for vvtt (429). Waiting 5s...
Rate/permission issue for vvtt (429). Waiting 10s...
Skipped after retries: vvtt
[454/1000] Fetching WOM details: VV B
Rate/permission issue for VV B (429). Waiting 5s...
Rate/permission issue for VV B (429). Waiting 10s...
Skipped after retries: VV B
[455/1000] Fetching WOM details: vvs comb alt
Rate/permission issue for vvs comb alt (429). Waiting 5s...
Rate/permission issue for vvs comb alt (429). Waiting 10s...
Skipped after retries: vvs comb alt
[456/1000] Fetching WOM details: vvBearded
Rate/permission issue for vvBearded (429). Waiting 5s...
[457/1000] Fetching WOM details: vv 10thPlace
[458/1000] Fetching WOM details: vvs
[459/1000] Fetching WOM details: Vvileeni
[460/1000] Fetching WOM details: VVillows
[461/1000] Fetching WOM details: vvjuul
[462/1000] Fetching WOM details: Vvlf
[463/1000] Fetching WOM details: VVegaClang
[464/1000] Fetching WOM details: VVBald
[465/1000] Fetching WOM details: vvvm
[466/1000] Fetching WOM details: VVintage
[467/1000] Fetching WOM details: vvm otter
[468/1000] Fetching WOM details: vvizu
[469/1000] Fetching WOM details: VVuLuZ
[470/1000] Fetching WOM details: VV Danko
[471/1000] Fetching WOM details: VVonky Camel
[472/1000] Fetching WOM details: Cn ii
[473/1000] Fetching WOM details: Cnr
[474/1000] Fetching WOM details: cnbl
[475/1000] Fetching WOM details: cno
[476/1000] Fetching WOM details: Cnhil
Rate/permission issue for Cnhil (429). Waiting 5s...
Rate/permission issue for Cnhil (429). Waiting 10s...
Skipped after retries: Cnhil
[477/1000] Fetching WOM details: CN0
Rate/permission issue for CN0 (429). Waiting 5s...
Rate/permission issue for CN0 (429). Waiting 10s...
Skipped after retries: CN0
[478/1000] Fetching WOM details: Cnnim
Rate/permission issue for Cnnim (429). Waiting 5s...
Rate/permission issue for Cnnim (429). Waiting 10s...
Skipped after retries: Cnnim
[479/1000] Fetching WOM details: CNN DonLemon
Rate/permission issue for CNN DonLemon (429). Waiting 5s...
[480/1000] Fetching WOM details: Cnyr
[481/1000] Fetching WOM details: CNHLAX 005
[482/1000] Fetching WOM details: Cnay
[483/1000] Fetching WOM details: CncrSpeedrun
[484/1000] Fetching WOM details: CnOadmee
[485/1000] Fetching WOM details: cnelly2
[486/1000] Fetching WOM details: cnopkes
[487/1000] Fetching WOM details: Cnun
[488/1000] Fetching WOM details: Cn hil
[489/1000] Fetching WOM details: CNPJota
[490/1000] Fetching WOM details: Cnsrv
[491/1000] Fetching WOM details: Cn Phantom
[492/1000] Fetching WOM details: GPA
[493/1000] Fetching WOM details: GPT
[494/1000] Fetching WOM details: Gp Over Hose
[495/1000] Fetching WOM details: gpdzosr
[496/1000] Fetching WOM details: gp for bags
[497/1000] Fetching WOM details: Gp Levioso
[498/1000] Fetching WOM details: Gp Saber
[499/1000] Fetching WOM details: GpGoesInBank
Rate/permission issue for GpGoesInBank (429). Waiting 5s...
Rate/permission issue for GpGoesInBank (429). Waiting 10s...
Skipped after retries: GpGoesInBank
[500/1000] Fetching WOM details: GPH00KZ
Rate/permission issue for GPH00KZ (429). Waiting 5s...
Rate/permission issue for GPH00KZ (429). Waiting 10s...
Skipped after retries: GPH00KZ
[501/1000] Fetching WOM details: gpfarm
Rate/permission issue for gpfarm (429). Waiting 5s...
Rate/permission issue for gpfarm (429). Waiting 10s...
Skipped after retries: gpfarm
[502/1000] Fetching WOM details: gp for ge
Rate/permission issue for gp for ge (429). Waiting 5s...
[503/1000] Fetching WOM details: gp294
[504/1000] Fetching WOM details: GPIMnuk
[505/1000] Fetching WOM details: GPIMJoel
[506/1000] Fetching WOM details: gptobill
[507/1000] Fetching WOM details: gp for OF
[508/1000] Fetching WOM details: gp conjuror
[509/1000] Fetching WOM details: gp coffer
[510/1000] Fetching WOM details: GP Senpai
[511/1000] Fetching WOM details: GP Grinder
[512/1000] Fetching WOM details: iFoRGe
[513/1000] Fetching WOM details: iFencig
[514/1000] Fetching WOM details: IFartOreos
[515/1000] Fetching WOM details: iFloono
[516/1000] Fetching WOM details: ifcruel
[517/1000] Fetching WOM details: ifantomas6
[518/1000] Fetching WOM details: IFoundABaby
[519/1000] Fetching WOM details: iFry
[520/1000] Fetching WOM details: iFalter
[521/1000] Fetching WOM details: If ykyk
[522/1000] Fetching WOM details: IFrac
Rate/permission issue for IFrac (429). Waiting 5s...
Rate/permission issue for IFrac (429). Waiting 10s...
Skipped after retries: IFrac
[523/1000] Fetching WOM details: if I may
Rate/permission issue for if I may (429). Waiting 5s...
Rate/permission issue for if I may (429). Waiting 10s...
Skipped after retries: if I may
[524/1000] Fetching WOM details: ifrogs
Rate/permission issue for ifrogs (429). Waiting 5s...
Rate/permission issue for ifrogs (429). Waiting 10s...
Skipped after retries: ifrogs
[525/1000] Fetching WOM details: IFBB Pro Joe
Rate/permission issue for IFBB Pro Joe (429). Waiting 5s...
[526/1000] Fetching WOM details: iFly a 767
[527/1000] Fetching WOM details: Iffyz
[528/1000] Fetching WOM details: ifightgiants
[529/1000] Fetching WOM details: IFRS 9
[530/1000] Fetching WOM details: ifemixi
[531/1000] Fetching WOM details: iFeaR3
[532/1000] Fetching WOM details: Cwick
[533/1000] Fetching WOM details: Cwazza
[534/1000] Fetching WOM details: Cwer

[535/1000] Fetching WOM details: cwum10
[536/1000] Fetching WOM details: cw90
[537/1000] Fetching WOM details: Cwiy
[538/1000] Fetching WOM details: Cw o
[539/1000] Fetching WOM details: Cwend
[540/1000] Fetching WOM details: cwan10
[541/1000] Fetching WOM details: Cwars Prod
[542/1000] Fetching WOM details: cwazi
[543/1000] Fetching WOM details: cwunchyroll
[544/1000] Fetching WOM details: Cwizzle69
[545/1000] Fetching WOM details: CWRL
Rate/permission issue for CWRL (429). Waiting 5s...
Rate/permission issue for CWRL (429). Waiting 10s...
Skipped after retries: CWRL
[546/1000] Fetching WOM details: cwisp damage
Rate/permission issue for cwisp damage (429). Waiting 5s...
Rate/permission issue for cwisp damage (429). Waiting 10s...
Skipped after retries: cwisp damage
[547/1000] Fetching WOM details: Cwaber
Rate/permission issue for Cwaber (429). Waiting 5s...
Rate/permission issue for Cwaber (429). Waiting 10s...
Skipped after retries: Cwaber
[548/1000] Fetching WOM details: cwob
Rate/permission issue for cwob (429). Waiting 5s...
[549/1000] Fetching WOM details: Cwaykid
[550/1000] Fetching WOM details: CWorldEnder
[551/1000] Fetching WOM details: cwzq
[552/1000] Fetching WOM details: Qthegreat
[553/1000] Fetching WOM details: qtpatooootie
[554/1000] Fetching WOM details: Qtey
[555/1000] Fetching WOM details: qtb
[556/1000] Fetching WOM details: qTiger
[557/1000] Fetching WOM details: qtei
[558/1000] Fetching WOM details: qt azn grill
[559/1000] Fetching WOM details: Qtu
[560/1000] Fetching WOM details: qtDeepFake
[561/1000] Fetching WOM details: qteifeetpics
[562/1000] Fetching WOM details: qtAshe
[563/1000] Fetching WOM details: qt
[564/1000] Fetching WOM details: qT Tp
[565/1000] Fetching WOM details: qt gf
[566/1000] Fetching WOM details: qt spring
[567/1000] Fetching WOM details: Qtbears
[568/1000] Fetching WOM details: qt0
Rate/permission issue for qt0 (429). Waiting 5s...
Rate/permission issue for qt0 (429). Waiting 10s...
Skipped after retries: qt0
[569/1000] Fetching WOM details: Qty
Rate/permission issue for Qty (429). Waiting 5s...
Rate/permission issue for Qty (429). Waiting 10s...
Skipped after retries: Qty
[570/1000] Fetching WOM details: qtchubbygirl
Rate/permission issue for qtchubbygirl (429). Waiting 5s...
Rate/permission issue for qtchubbygirl (429). Waiting 10s...
Skipped after retries: qtchubbygirl
[571/1000] Fetching WOM details: Qtr Lb
Rate/permission issue for Qtr Lb (429). Waiting 5s...
[572/1000] Fetching WOM details: 1lI1Ill1Il1l
[573/1000] Fetching WOM details: 1LizardLove
[574/1000] Fetching WOM details: 1likepikachu
[575/1000] Fetching WOM details: 1lifeBilo
[576/1000] Fetching WOM details: 1Life Kura
[577/1000] Fetching WOM details: 1li1
[578/1000] Fetching WOM details: 1lifebelvojr
[579/1000] Fetching WOM details: 1LIFE FARMER
[580/1000] Fetching WOM details: 1Life0Hecks
[581/1000] Fetching WOM details: 1lifeclogger
[582/1000] Fetching WOM details: 1lifeatatime
[583/1000] Fetching WOM details: 1lifenogulag
[584/1000] Fetching WOM details: 1liam os
[585/1000] Fetching WOM details: 1likefeet
[586/1000] Fetching WOM details: 1lifeteezy
[587/1000] Fetching WOM details: 1lii
[588/1000] Fetching WOM details: 1lilkiller
[589/1000] Fetching WOM details: 1LifeBelvo
[590/1000] Fetching WOM details: 1LITTLEBOY1
[591/1000] Fetching WOM details: 1LifeNoWife
Rate/permission issue for 1LifeNoWife (429). Waiting 5s...
Rate/permission issue for 1LifeNoWife (429). Waiting 10s...
Skipped after retries: 1LifeNoWife
[592/1000] Fetching WOM details: jcjustdoit24
Rate/permission issue for jcjustdoit24 (429). Waiting 5s...
Rate/permission issue for jcjustdoit24 (429). Waiting 10s...
Skipped after retries: jcjustdoit24
[593/1000] Fetching WOM details: 03Halo
Rate/permission issue for 03Halo (429). Waiting 5s...
Rate/permission issue for 03Halo (429). Waiting 10s...
Skipped after retries: 03Halo
[594/1000] Fetching WOM details: 03x
Rate/permission issue for 03x (429). Waiting 5s...
[595/1000] Fetching WOM details: 0311
[596/1000] Fetching WOM details: 03gp
[597/1000] Fetching WOM details: 035 Ironman
[598/1000] Fetching WOM details: 038 Zwolle
[599/1000] Fetching WOM details: 03h
[600/1000] Fetching WOM details: 03geeko
[601/1000] Fetching WOM details: 038jasper
[602/1000] Fetching WOM details: 03gredo
[603/1000] Fetching WOM details: 0390
[604/1000] Fetching WOM details: 036jttairon
[605/1000] Fetching WOM details: 03Sol
[606/1000] Fetching WOM details: 03 Not Laugh
[607/1000] Fetching WOM details: 03 flow
[608/1000] Fetching WOM details: 03 tw
[609/1000] Fetching WOM details: 03LUIS03
[610/1000] Fetching WOM details: 033022
[611/1000] Fetching WOM details: 03mcclintock
[612/1000] Fetching WOM details: 03osrs
[613/1000] Fetching WOM details: I0u2
[614/1000] Fetching WOM details: HANDSS55HAKE
Rate/permission issue for HANDSS55HAKE (429). Waiting 5s...
Rate/permission issue for HANDSS55HAKE (429). Waiting 10s...
Skipped after retries: HANDSS55HAKE
[615/1000] Fetching WOM details: HANDS55SHAKE
Rate/permission issue for HANDS55SHAKE (429). Waiting 5s...
Rate/permission issue for HANDS55SHAKE (429). Waiting 10s...
Skipped after retries: HANDS55SHAKE
[616/1000] Fetching WOM details: Harmony
Rate/permission issue for Harmony (429). Waiting 5s...
Rate/permission issue for Harmony (429). Waiting 10s...
Skipped after retries: Harmony
[617/1000] Fetching WOM details: HAHAFREAKYES
Rate/permission issue for HAHAFREAKYES (429). Waiting 5s...
[618/1000] Fetching WOM details: hae yoon
[619/1000] Fetching WOM details: Haw
[620/1000] Fetching WOM details: HADJ
[621/1000] Fetching WOM details: Haydz
[622/1000] Fetching WOM details: hailuo
[623/1000] Fetching WOM details: Hampus
[624/1000] Fetching WOM details: Hasbullah
[625/1000] Fetching WOM details: Hands Up
[626/1000] Fetching WOM details: Halla Aho
[627/1000] Fetching WOM details: Hattibagen
[628/1000] Fetching WOM details: hadies205
[629/1000] Fetching WOM details: Happy Beluga
[630/1000] Fetching WOM details: Hang em high
[631/1000] Fetching WOM details: Hardie
[632/1000] Fetching WOM details: Ha tsi
[633/1000] Fetching WOM details: Harja
[634/1000] Fetching WOM details: Qdablock
[635/1000] Fetching WOM details: qddq
[636/1000] Fetching WOM details: qdonkey
[637/1000] Fetching WOM details: qdoba28
Rate/permission issue for qdoba28 (429). Waiting 5s...
Rate/permission issue for qdoba28 (429). Waiting 10s...
Skipped after retries: qdoba28
[638/1000] Fetching WOM details: QD alpha 69
Rate/permission issue for QD alpha 69 (429). Waiting 5s...
Rate/permission issue for QD alpha 69 (429). Waiting 10s...
Skipped after retries: QD alpha 69
[639/1000] Fetching WOM details: qdmd
Rate/permission issue for qdmd (429). Waiting 5s...
Rate/permission issue for qdmd (429). Waiting 10s...
Skipped after retries: qdmd
[640/1000] Fetching WOM details: QDestroyer
Rate/permission issue for QDestroyer (429). Waiting 5s...
[641/1000] Fetching WOM details: QdpqbQ
[642/1000] Fetching WOM details: QD0GG
[643/1000] Fetching WOM details: qdcents
[644/1000] Fetching WOM details: qdaan
[645/1000] Fetching WOM details: qdance
[646/1000] Fetching WOM details: qdn
[647/1000] Fetching WOM details: qdmc
[648/1000] Fetching WOM details: Qdvil
[649/1000] Fetching WOM details: qdrunk
[650/1000] Fetching WOM details: QDCH
[651/1000] Fetching WOM details: QDABLQCK
[652/1000] Fetching WOM details: qDano
[653/1000] Fetching WOM details: qdz
[654/1000] Fetching WOM details: TKZA
[655/1000] Fetching WOM details: Tkz2410
[656/1000] Fetching WOM details: Tkzuk MeDadd
[657/1000] Fetching WOM details: Tkz Valor
[658/1000] Fetching WOM details: GW33D
[659/1000] Fetching WOM details: gw3n
[660/1000] Fetching WOM details: 20QP
Rate/permission issue for 20QP (429). Waiting 5s...
Rate/permission issue for 20QP (429). Waiting 10s...
Skipped after retries: 20QP
[661/1000] Fetching WOM details: 20QuidOfYiff
Rate/permission issue for 20QuidOfYiff (429). Waiting 5s...
Rate/permission issue for 20QuidOfYiff (429). Waiting 10s...
Skipped after retries: 20QuidOfYiff
[662/1000] Fetching WOM details: 20quish08
Rate/permission issue for 20quish08 (429). Waiting 5s...
[663/1000] Fetching WOM details: 20quid
[664/1000] Fetching WOM details: KswisherMuh
[665/1000] Fetching WOM details: Kswag

[666/1000] Fetching WOM details: Ksw1sh3r
[667/1000] Fetching WOM details: ksw
[668/1000] Fetching WOM details: Kswizz
[669/1000] Fetching WOM details: Kswann
[670/1000] Fetching WOM details: kswan
[671/1000] Fetching WOM details: kswizzy
[672/1000] Fetching WOM details: kswan14
[673/1000] Fetching WOM details: KSWVEC
[674/1000] Fetching WOM details: kswilly bets
[675/1000] Fetching WOM details: Kswivel
[676/1000] Fetching WOM details: 5x7
[677/1000] Fetching WOM details: b2p teemo
[678/1000] Fetching WOM details: b2p v2
[679/1000] Fetching WOM details: b2p
[680/1000] Fetching WOM details: b2p brigade
[681/1000] Fetching WOM details: b2pure
[682/1000] Fetching WOM details: B2P Grim9
Rate/permission issue for B2P Grim9 (429). Waiting 5s...
Rate/permission issue for B2P Grim9 (429). Waiting 10s...
Skipped after retries: B2P Grim9
[683/1000] Fetching WOM details: b2p host
Rate/permission issue for b2p host (429). Waiting 5s...
Rate/permission issue for b2p host (429). Waiting 10s...
Skipped after retries: b2p host
[684/1000] Fetching WOM details: b2pk
Rate/permission issue for b2pk (429). Waiting 5s...
Rate/permission issue for b2pk (429). Waiting 10s...
Skipped after retries: b2pk
[685/1000] Fetching WOM details: B2Pop
Rate/permission issue for B2Pop (429). Waiting 5s...
[686/1000] Fetching WOM details: Przyszlak
[687/1000] Fetching WOM details: Przyner
[688/1000] Fetching WOM details: Przthespeedy
[689/1000] Fetching WOM details: Przc
[690/1000] Fetching WOM details: Przymiot
[691/1000] Fetching WOM details: przyn
[692/1000] Fetching WOM details: Prztheump
[693/1000] Fetching WOM details: przelda1234
[694/1000] Fetching WOM details: prze
[695/1000] Fetching WOM details: Przemzz
[696/1000] Fetching WOM details: przemxde
[697/1000] Fetching WOM details: Przystupa542
[698/1000] Fetching WOM details: przcamacho
[699/1000] Fetching WOM details: Przeck
[700/1000] Fetching WOM details: Przemas SQ
[701/1000] Fetching WOM details: przetrwac
[702/1000] Fetching WOM details: Przybycien28
[703/1000] Fetching WOM details: PrzNoKirrMe
[704/1000] Fetching WOM details: przzzzz
[705/1000] Fetching WOM details: prz schlap
Rate/permission issue for prz schlap (429). Waiting 5s...
Rate/permission issue for prz schlap (429). Waiting 10s...
Skipped after retries: prz schlap
[706/1000] Fetching WOM details: Zoik
Rate/permission issue for Zoik (429). Waiting 5s...
Rate/permission issue for Zoik (429). Waiting 10s...
Skipped after retries: Zoik
[707/1000] Fetching WOM details: zoinker
Rate/permission issue for zoinker (429). Waiting 5s...
Rate/permission issue for zoinker (429). Waiting 10s...
Skipped after retries: zoinker
[708/1000] Fetching WOM details: Zoingbober
Rate/permission issue for Zoingbober (429). Waiting 5s...
[709/1000] Fetching WOM details: Zoidie
[710/1000] Fetching WOM details: Zoinks Bro
[711/1000] Fetching WOM details: zoinque
[712/1000] Fetching WOM details: Zoido
[713/1000] Fetching WOM details: Zoilus
[714/1000] Fetching WOM details: Zoidzaker
[715/1000] Fetching WOM details: zoifa
[716/1000] Fetching WOM details: Zoinkwiz
[717/1000] Fetching WOM details: zoinks97
[718/1000] Fetching WOM details: Zoide
[719/1000] Fetching WOM details: Zoinxs
[720/1000] Fetching WOM details: Zoicers
[721/1000] Fetching WOM details: Zoinke
[722/1000] Fetching WOM details: ZoidbergJ
[723/1000] Fetching WOM details: Zoinks Scoob
[724/1000] Fetching WOM details: Zoil
[725/1000] Fetching WOM details: Zoid
[726/1000] Fetching WOM details: 9u9
[727/1000] Fetching WOM details: 9uglyiguana
[728/1000] Fetching WOM details: 9udge
Rate/permission issue for 9udge (429). Waiting 5s...
Rate/permission issue for 9udge (429). Waiting 10s...
Skipped after retries: 9udge
[729/1000] Fetching WOM details: 9ueen
Rate/permission issue for 9ueen (429). Waiting 5s...
Rate/permission issue for 9ueen (429). Waiting 10s...
Skipped after retries: 9ueen
[730/1000] Fetching WOM details: 9urp
Rate/permission issue for 9urp (429). Waiting 5s...
Rate/permission issue for 9urp (429). Waiting 10s...
Skipped after retries: 9urp
[731/1000] Fetching WOM details: 9ueeflatifah
Rate/permission issue for 9ueeflatifah (429). Waiting 5s...
[732/1000] Fetching WOM details: 9uns
[733/1000] Fetching WOM details: 9uetzal
[734/1000] Fetching WOM details: 9ur3 0wns
[735/1000] Fetching WOM details: 9uthixmage
[736/1000] Fetching WOM details: 9uester
[737/1000] Fetching WOM details: 9ure or P1es
[738/1000] Fetching WOM details: 9uit
[739/1000] Fetching WOM details: 9uin
[740/1000] Fetching WOM details: 9ums
[741/1000] Fetching WOM details: 9ussy
[742/1000] Fetching WOM details: 9undead1532
[743/1000] Fetching WOM details: 9uj
[744/1000] Fetching WOM details: 9uinn
[745/1000] Fetching WOM details: 9u8
[746/1000] Fetching WOM details: Qdt457
[747/1000] Fetching WOM details: 84wornpony6
[748/1000] Fetching WOM details: 84wise2478
[749/1000] Fetching WOM details: Hjaldr
[750/1000] Fetching WOM details: Hjuki
[751/1000] Fetching WOM details: Hjb
Rate/permission issue for Hjb (429). Waiting 5s...
Rate/permission issue for Hjb (429). Waiting 10s...
Skipped after retries: Hjb
[752/1000] Fetching WOM details: hjenzen
Rate/permission issue for hjenzen (429). Waiting 5s...
Rate/permission issue for hjenzen (429). Waiting 10s...
Skipped after retries: hjenzen
[753/1000] Fetching WOM details: hj7
Rate/permission issue for hj7 (429). Waiting 5s...
Rate/permission issue for hj7 (429). Waiting 10s...
Skipped after retries: hj7
[754/1000] Fetching WOM details: Hjalti181
Rate/permission issue for Hjalti181 (429). Waiting 5s...
[755/1000] Fetching WOM details: hjerneskada
[756/1000] Fetching WOM details: hj 1
[757/1000] Fetching WOM details: hjea
[758/1000] Fetching WOM details: hj4u
[759/1000] Fetching WOM details: HJVapen
[760/1000] Fetching WOM details: HJYD
[761/1000] Fetching WOM details: HJBa
[762/1000] Fetching WOM details: HjoZ
[763/1000] Fetching WOM details: Hjbi
[764/1000] Fetching WOM details: HJD
[765/1000] Fetching WOM details: hjit izer
[766/1000] Fetching WOM details: hjhohnh wicc
[767/1000] Fetching WOM details: Hjonathan
[768/1000] Fetching WOM details: hjm
[769/1000] Fetching WOM details: Q7L
[770/1000] Fetching WOM details: q7f
[771/1000] Fetching WOM details: q7d
[772/1000] Fetching WOM details: Q7 1
[773/1000] Fetching WOM details: q7g
[774/1000] Fetching WOM details: q7s
Rate/permission issue for q7s (429). Waiting 5s...
Rate/permission issue for q7s (429). Waiting 10s...
Skipped after retries: q7s
[775/1000] Fetching WOM details: q7
Rate/permission issue for q7 (429). Waiting 5s...
Rate/permission issue for q7 (429). Waiting 10s...
Skipped after retries: q7
[776/1000] Fetching WOM details: q73
Rate/permission issue for q73 (429). Waiting 5s...
Rate/permission issue for q73 (429). Waiting 10s...
Skipped after retries: q73
[777/1000] Fetching WOM details: q7a tempest
Rate/permission issue for q7a tempest (429). Waiting 5s...
[778/1000] Fetching WOM details: Q7ls Scout
[779/1000] Fetching WOM details: O6OO
[780/1000] Fetching WOM details: O6og
[781/1000] Fetching WOM details: G1izzyGob1in
[782/1000] Fetching WOM details: G1ITI
[783/1000] Fetching WOM details: g1itterkitty
[784/1000] Fetching WOM details: G1ibG1ob
[785/1000] Fetching WOM details: g1izzard
[786/1000] Fetching WOM details: G1izzyGuard
[787/1000] Fetching WOM details: g1izzygob1n
[788/1000] Fetching WOM details: g1iz
[789/1000] Fetching WOM details: G1imps
[790/1000] Fetching WOM details: g1izzy bear
[791/1000] Fetching WOM details: G1IrnMnLath
[792/1000] Fetching WOM details: I9l92l8I2lM9
[793/1000] Fetching WOM details: iv4n ooze
[794/1000] Fetching WOM details: iv4nthegr8
[795/1000] Fetching WOM details: iv4
[796/1000] Fetching WOM details: IV4BE RA L
[797/1000] Fetching WOM details: iv4nn
Rate/permission issue for iv4nn (429). Waiting 5s...
Rate/permission issue for iv4nn (429). Waiting 10s...
Skipped after retries: iv4nn
[798/1000] Fetching WOM details: xsensei
Rate/permission issue for xsensei (429). Waiting 5s...
Rate/permission issue for xsensei (429). Waiting 10s...
Skipped after retries: xsensei
[799/1000] Fetching WOM details: xSweetDreamz
Rate/permission issue for xSweetDreamz (429). Waiting 5s...
Rate/permission issue for xSweetDreamz (429). Waiting 10s...

Skipped after retries: xSweetDreamz
[800/1000] Fetching WOM details: xstuart
Rate/permission issue for xstuart (429). Waiting 5s...
[801/1000] Fetching WOM details: xSleepgoodx
[802/1000] Fetching WOM details: xsantcastx
[803/1000] Fetching WOM details: xSouls
[804/1000] Fetching WOM details: xScrafty
[805/1000] Fetching WOM details: Xsk1l3rX
[806/1000] Fetching WOM details: xSxAxMx
[807/1000] Fetching WOM details: xSach
[808/1000] Fetching WOM details: xSteelbeardx
[809/1000] Fetching WOM details: xsomethingxd
[810/1000] Fetching WOM details: xSnik
[811/1000] Fetching WOM details: xSlayer
[812/1000] Fetching WOM details: xShady
[813/1000] Fetching WOM details: xSynna
[814/1000] Fetching WOM details: xSeori
[815/1000] Fetching WOM details: xsoar
[816/1000] Fetching WOM details: xsaby
[817/1000] Fetching WOM details: xsmall
[818/1000] Fetching WOM details: W489
[819/1000] Fetching WOM details: w488 imp
[820/1000] Fetching WOM details: w48smage
Rate/permission issue for w48smage (429). Waiting 5s...
Rate/permission issue for w48smage (429). Waiting 10s...
Skipped after retries: w48smage
[821/1000] Fetching WOM details: W487
Rate/permission issue for W487 (429). Waiting 5s...
Rate/permission issue for W487 (429). Waiting 10s...
Skipped after retries: W487
[822/1000] Fetching WOM details: W488
Rate/permission issue for W488 (429). Waiting 5s...
Rate/permission issue for W488 (429). Waiting 10s...
Skipped after retries: W488
[823/1000] Fetching WOM details: w486
Rate/permission issue for w486 (429). Waiting 5s...
[824/1000] Fetching WOM details: NBrenna
[825/1000] Fetching WOM details: nbdallday
[826/1000] Fetching WOM details: NBDucK
[827/1000] Fetching WOM details: Nbj6
[828/1000] Fetching WOM details: Nb1992
[829/1000] Fetching WOM details: nbyo
[830/1000] Fetching WOM details: nbui
[831/1000] Fetching WOM details: nbea
[832/1000] Fetching WOM details: NBA
[833/1000] Fetching WOM details: nBnx
[834/1000] Fetching WOM details: nby
[835/1000] Fetching WOM details: Nbomb Tom
[836/1000] Fetching WOM details: NBAyoungboy
[837/1000] Fetching WOM details: NBA Youngb0i
[838/1000] Fetching WOM details: nb16
[839/1000] Fetching WOM details: nbmo
[840/1000] Fetching WOM details: NBLS
[841/1000] Fetching WOM details: nBoots
[842/1000] Fetching WOM details: Nburi
[843/1000] Fetching WOM details: nblakeey
Rate/permission issue for nblakeey (429). Waiting 5s...
Rate/permission issue for nblakeey (429). Waiting 10s...
Skipped after retries: nblakeey
[844/1000] Fetching WOM details: Vylet
Rate/permission issue for Vylet (429). Waiting 5s...
Rate/permission issue for Vylet (429). Waiting 10s...
Skipped after retries: Vylet
[845/1000] Fetching WOM details: vyeborg
Rate/permission issue for vyeborg (429). Waiting 5s...
Rate/permission issue for vyeborg (429). Waiting 10s...
Skipped after retries: vyeborg
[846/1000] Fetching WOM details: Vywe
Rate/permission issue for Vywe (429). Waiting 5s...
[847/1000] Fetching WOM details: Vymera
[848/1000] Fetching WOM details: vyvids
[849/1000] Fetching WOM details: vya
[850/1000] Fetching WOM details: vynariian
[851/1000] Fetching WOM details: Vynom
[852/1000] Fetching WOM details: Vyrelady Em
[853/1000] Fetching WOM details: Vyrelord
[854/1000] Fetching WOM details: vypa100
[855/1000] Fetching WOM details: Vyve
[856/1000] Fetching WOM details: vynly
[857/1000] Fetching WOM details: vyncenz
[858/1000] Fetching WOM details: Vytauts
[859/1000] Fetching WOM details: Vykz
[860/1000] Fetching WOM details: vys 6 7
[861/1000] Fetching WOM details: vyseny
[862/1000] Fetching WOM details: vyrdin
[863/1000] Fetching WOM details: Vyukris
[864/1000] Fetching WOM details: Xx99xX
[865/1000] Fetching WOM details: xx9
[866/1000] Fetching WOM details: xx99lokuraxx
Rate/permission issue for xx99lokuraxx (429). Waiting 5s...
Rate/permission issue for xx99lokuraxx (429). Waiting 10s...
Skipped after retries: xx99lokuraxx
[867/1000] Fetching WOM details: xx93xx
Rate/permission issue for xx93xx (429). Waiting 5s...
Rate/permission issue for xx93xx (429). Waiting 10s...
Skipped after retries: xx93xx
[868/1000] Fetching WOM details: xx99strpk0x
Rate/permission issue for xx99strpk0x (429). Waiting 5s...
Rate/permission issue for xx99strpk0x (429). Waiting 10s...
Skipped after retries: xx99strpk0x
[869/1000] Fetching WOM details: xx9b
Rate/permission issue for xx9b (429). Waiting 5s...
[870/1000] Fetching WOM details: Xx9mmxX
[871/1000] Fetching WOM details: xX95king
[872/1000] Fetching WOM details: xx999xy
[873/1000] Fetching WOM details: xx99xx99xxpk
[874/1000] Fetching WOM details: xx90gu
[875/1000] Fetching WOM details: C2Q
[876/1000] Fetching WOM details: NZ Timzee
[877/1000] Fetching WOM details: NZ miler
[878/1000] Fetching WOM details: Nzz
[879/1000] Fetching WOM details: NZ warriors
[880/1000] Fetching WOM details: nz btw
[881/1000] Fetching WOM details: nz drogon
[882/1000] Fetching WOM details: NZTP
[883/1000] Fetching WOM details: NZ Dave
[884/1000] Fetching WOM details: Nzpkers
[885/1000] Fetching WOM details: nz irontitan
[886/1000] Fetching WOM details: nz unlucky
[887/1000] Fetching WOM details: Nzgul
[888/1000] Fetching WOM details: Nz boy 96
[889/1000] Fetching WOM details: NzTopTeam
Rate/permission issue for NzTopTeam (429). Waiting 5s...
Rate/permission issue for NzTopTeam (429). Waiting 10s...
Skipped after retries: NzTopTeam
[890/1000] Fetching WOM details: Nz Assassin
Rate/permission issue for Nz Assassin (429). Waiting 5s...
Rate/permission issue for Nz Assassin (429). Waiting 10s...
Skipped after retries: Nz Assassin
[891/1000] Fetching WOM details: NZ Madfrog
Rate/permission issue for NZ Madfrog (429). Waiting 5s...
Rate/permission issue for NZ Madfrog (429). Waiting 10s...
Skipped after retries: NZ Madfrog
[892/1000] Fetching WOM details: nzurisana
Rate/permission issue for nzurisana (429). Waiting 5s...
[893/1000] Fetching WOM details: NZ Titan
[894/1000] Fetching WOM details: nz iron 07
[895/1000] Fetching WOM details: nzl
[896/1000] Fetching WOM details: 8u2
[897/1000] Fetching WOM details: Cmkrs
[898/1000] Fetching WOM details: CMKrellan
[899/1000] Fetching WOM details: Klxx
[900/1000] Fetching WOM details: Klxmmiii
[901/1000] Fetching WOM details: klx110l
[902/1000] Fetching WOM details: qyrk
[903/1000] Fetching WOM details: QY
[904/1000] Fetching WOM details: Qyana
[905/1000] Fetching WOM details: QynixGnome
[906/1000] Fetching WOM details: Qyty
[907/1000] Fetching WOM details: Qyzr
[908/1000] Fetching WOM details: qyxxdio
[909/1000] Fetching WOM details: Qyd
[910/1000] Fetching WOM details: qyz
[911/1000] Fetching WOM details: Qyix
[912/1000] Fetching WOM details: Qyzs
Rate/permission issue for Qyzs (429). Waiting 5s...
Rate/permission issue for Qyzs (429). Waiting 10s...
Skipped after retries: Qyzs
[913/1000] Fetching WOM details: QY1
Rate/permission issue for QY1 (429). Waiting 5s...
Rate/permission issue for QY1 (429). Waiting 10s...
Skipped after retries: QY1
[914/1000] Fetching WOM details: Qyrx
Rate/permission issue for Qyrx (429). Waiting 5s...
Rate/permission issue for Qyrx (429). Waiting 10s...
Skipped after retries: Qyrx
[915/1000] Fetching WOM details: Qyiz
Rate/permission issue for Qyiz (429). Waiting 5s...
[916/1000] Fetching WOM details: qyt
[917/1000] Fetching WOM details: qY Yp
[918/1000] Fetching WOM details: Qyme
[919/1000] Fetching WOM details: qysh je
[920/1000] Fetching WOM details: Qyrrr
[921/1000] Fetching WOM details: qyuh
[922/1000] Fetching WOM details: nu0rin
[923/1000] Fetching WOM details: nu0c
[924/1000] Fetching WOM details: nu0rin god
[925/1000] Fetching WOM details: nu0rion
[926/1000] Fetching WOM details: 03v
[927/1000] Fetching WOM details: 2x2 base
[928/1000] Fetching WOM details: 2x3
[929/1000] Fetching WOM details: 2xdx
[930/1000] Fetching WOM details: 2x h
[931/1000] Fetching WOM details: 2x Agent
[932/1000] Fetching WOM details: 2x4x16
[933/1000] Fetching WOM details: 2xpee2xpoo
[934/1000] Fetching WOM details: 2x Airfried
[935/1000] Fetching WOM details: 2xStitched
Rate/permission issue for 2xStitched (429). Waiting 5s...
Rate/permission issue for 2xStitched (429). Waiting 10s...
Skipped after retries: 2xStitched
[936/1000] Fetching WOM details: 2xUniverse
Rate/permission issue for 2xUniverse (429). Waiting 5s...

Rate/permission issue for 2xUniverse (429). Waiting 10s...
Skipped after retries: 2xUniverse
[937/1000] Fetching WOM details: 2x50
Rate/permission issue for 2x50 (429). Waiting 5s...
Rate/permission issue for 2x50 (429). Waiting 10s...
Skipped after retries: 2x50
[938/1000] Fetching WOM details: 2x92is99
Rate/permission issue for 2x92is99 (429). Waiting 5s...
[939/1000] Fetching WOM details: 2xshine
[940/1000] Fetching WOM details: 2xLightning
[941/1000] Fetching WOM details: 2x Tychy
[942/1000] Fetching WOM details: 2x210
[943/1000] Fetching WOM details: 2x8
[944/1000] Fetching WOM details: 2x Drops
[945/1000] Fetching WOM details: 2x Enh Dr
[946/1000] Fetching WOM details: 2xRice0Veggi
[947/1000] Fetching WOM details: PG4GP
[948/1000] Fetching WOM details: Fuyaning
[949/1000] Fetching WOM details: Fuyan
[950/1000] Fetching WOM details: J4S
[951/1000] Fetching WOM details: J4my
[952/1000] Fetching WOM details: J4COBI
[953/1000] Fetching WOM details: J4ymond
[954/1000] Fetching WOM details: J4ws
[955/1000] Fetching WOM details: j4a
[956/1000] Fetching WOM details: J4mi
[957/1000] Fetching WOM details: J4 K E
[958/1000] Fetching WOM details: j4mb0ree
Rate/permission issue for j4mb0ree (429). Waiting 5s...
Rate/permission issue for j4mb0ree (429). Waiting 10s...
Skipped after retries: j4mb0ree
[959/1000] Fetching WOM details: J4YG
Rate/permission issue for J4YG (429). Waiting 5s...
Rate/permission issue for J4YG (429). Waiting 10s...
Skipped after retries: J4YG
[960/1000] Fetching WOM details: J49
Rate/permission issue for J49 (429). Waiting 5s...
Rate/permission issue for J49 (429). Waiting 10s...
Skipped after retries: J49
[961/1000] Fetching WOM details: J4MS
Rate/permission issue for J4MS (429). Waiting 5s...
[962/1000] Fetching WOM details: j4sp3r7
[963/1000] Fetching WOM details: J4Z3
[964/1000] Fetching WOM details: j4ma
[965/1000] Fetching WOM details: j4ice wrld
[966/1000] Fetching WOM details: j4lb
[967/1000] Fetching WOM details: J4F
[968/1000] Fetching WOM details: J4bes
[969/1000] Fetching WOM details: J4ckFr0zt
[970/1000] Fetching WOM details: rf scott
[971/1000] Fetching WOM details: rf s
[972/1000] Fetching WOM details: rf2f2f23f32f
[973/1000] Fetching WOM details: rflars
[974/1000] Fetching WOM details: RF Kill
[975/1000] Fetching WOM details: rf kein
[976/1000] Fetching WOM details: rfm
[977/1000] Fetching WOM details: Rfz
[978/1000] Fetching WOM details: RFU
[979/1000] Fetching WOM details: rfenske1234
[980/1000] Fetching WOM details: RFC Mutagen
[981/1000] Fetching WOM details: Rfsu
Rate/permission issue for Rfsu (429). Waiting 5s...
Rate/permission issue for Rfsu (429). Waiting 10s...
Skipped after retries: Rfsu
[982/1000] Fetching WOM details: RFB
Rate/permission issue for RFB (429). Waiting 5s...
Rate/permission issue for RFB (429). Waiting 10s...
Skipped after retries: RFB
[983/1000] Fetching WOM details: Rfd
Rate/permission issue for Rfd (429). Waiting 5s...
Rate/permission issue for Rfd (429). Waiting 10s...
Skipped after retries: Rfd
[984/1000] Fetching WOM details: RFDS
Rate/permission issue for RFDS (429). Waiting 5s...
[985/1000] Fetching WOM details: rfscs
[986/1000] Fetching WOM details: rffh
[987/1000] Fetching WOM details: RFBEAN
[988/1000] Fetching WOM details: RF No1s
[989/1000] Fetching WOM details: rfr0sti
[990/1000] Fetching WOM details: p3ych0
[991/1000] Fetching WOM details: KDsBurnerAcc
[992/1000] Fetching WOM details: kds141197
[993/1000] Fetching WOM details: kdsnfmo
[994/1000] Fetching WOM details: Kdst radio
[995/1000] Fetching WOM details: kdstudios
[996/1000] Fetching WOM details: kdsuperhero
[997/1000] Fetching WOM details: kdst
[998/1000] Fetching WOM details: kdslo
[999/1000] Fetching WOM details: kdsfdds
[1000/1000] Fetching WOM details: kds

,player,overall_rank,overall_level,overall_xp,attack_rank,attack_level,attack_xp,defence_rank,defence_level,defence_xp,...,pvp_arena_rank,pvp_arena_score,soul_wars_zeal_rank,soul_wars_zeal_score,guardians_of_the_rift_rank,guardians_of_the_rift_score,colosseum_glory_rank,colosseum_glory_score,collections_logged_rank,collections_logged_score
0,Obbyy,3606.0,2376.0,1.055380e+09,60190.0,99.0,25735539.0,15708.0,99.0,32203282.0,...,-1.0,2500.0,-1.0,0.0,761269.0,31.0,108255.0,23054.0,20558.0,840.0
1,Obby Cape,6936.0,2376.0,5.371348e+08,21439.0,99.0,18904741.0,8059.0,99.0,24819279.0,...,-1.0,2126.0,959.0,39003.0,14201.0,483.0,43031.0,637.0,2665.0,1091.0
2,Obby Apples,93294.0,2278.0,9.500952e+08,98436.0,99.0,21090532.0,136.0,99.0,200000000.0,...,-1.0,2500.0,-1.0,0.0,-1.0,0.0,-1.0,0.0,-1.0,157.0
3,Obby Kenobi,1008395.0,1750.0,2.861366e+08,-1.0,1.0,40.0,-1.0,1.0,0.0,...,-1.0,2500.0,194209.0,315.0,645805.0,45.0,-1.0,0.0,-1.0,96.0
4,obbE x,23800.0,2376.0,5.214336e+08,218871.0,99.0,15566135.0,47096.0,99.0,22895521.0,...,-1.0,2500.0,-1.0,0.0,367807.0,127.0,31651.0,40148.0,51659.0,657.0

In [57]:
[column for column in df_hiscores.columns if column.endswith("_kc")][:30]

['abyssal_sire_kc',
 'alchemical_hydra_kc',
 'amoxliatl_kc',
 'araxxor_kc',
 'artio_kc',
 'barrows_chests_kc',
 'brutus_kc',
 'bryophyta_kc',
 'callisto_kc',
 'calvarion_kc',
 'cerberus_kc',
 'chambers_of_xeric_kc',
 'chambers_of_xeric_challenge_mode_kc',
 'chaos_elemental_kc',
 'chaos_fanatic_kc',
 'commander_zilyana_kc',
 'corporeal_beast_kc',
 'crazy_archaeologist_kc',
 'dagannoth_prime_kc',
 'dagannoth_rex_kc',
 'dagannoth_supreme_kc',
 'deranged_archaeologist_kc',
 'doom_of_mokhaiotl_kc',
 'duke_sucellus_kc',
 'general_graardor_kc',
 'giant_mole_kc',
 'grotesque_guardians_kc',
 'hespori_kc',
 'kalphite_queen_kc',
 'king_black_dragon_kc']

In [60]:
df_hiscores[df_hiscores["player"].str.lower() == "RFU"][
    ["player", "cerberus_kc"]
]

Empty DataFrame
Columns: [player, cerberus_kc]
Index: []

## 13. Inspect collected Hiscores dataset

Before saving the dataset, basic checks are performed.

In [61]:
df_hiscores.shape

(874, 244)

In [62]:
df_hiscores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 874 entries, 0 to 873
Columns: 244 entries, player to collections_logged_score
dtypes: float64(243), object(1)
memory usage: 1.6+ MB

In [64]:
df_hiscores.head()

,player,overall_rank,overall_level,overall_xp,attack_rank,attack_level,attack_xp,defence_rank,defence_level,defence_xp,...,pvp_arena_rank,pvp_arena_score,soul_wars_zeal_rank,soul_wars_zeal_score,guardians_of_the_rift_rank,guardians_of_the_rift_score,colosseum_glory_rank,colosseum_glory_score,collections_logged_rank,collections_logged_score
0,Obbyy,3606.0,2376.0,1.055380e+09,60190.0,99.0,25735539.0,15708.0,99.0,32203282.0,...,-1.0,2500.0,-1.0,0.0,761269.0,31.0,108255.0,23054.0,20558.0,840.0
1,Obby Cape,6936.0,2376.0,5.371348e+08,21439.0,99.0,18904741.0,8059.0,99.0,24819279.0,...,-1.0,2126.0,959.0,39003.0,14201.0,483.0,43031.0,637.0,2665.0,1091.0
2,Obby Apples,93294.0,2278.0,9.500952e+08,98436.0,99.0,21090532.0,136.0,99.0,200000000.0,...,-1.0,2500.0,-1.0,0.0,-1.0,0.0,-1.0,0.0,-1.0,157.0
3,Obby Kenobi,1008395.0,1750.0,2.861366e+08,-1.0,1.0,40.0,-1.0,1.0,0.0,...,-1.0,2500.0,194209.0,315.0,645805.0,45.0,-1.0,0.0,-1.0,96.0
4,obbE x,23800.0,2376.0,5.214336e+08,218871.0,99.0,15566135.0,47096.0,99.0,22895521.0,...,-1.0,2500.0,-1.0,0.0,367807.0,127.0,31651.0,40148.0,51659.0,657.0

In [65]:
len(failed_players), failed_players[:20]

(126,
 ['obby chkn',
  'xPottz',
  'xpotatoex',
  'i42O',
  'ws daplug',
  'WS ZaIc',
  'WSedanOwner',
  'dmoz',
  'dm 4 pawjob',
  'dmb',
  'n6s8tb2an7p',
  '0rthru5',
  '0regy',
  'NVREVRLUCKY',
  'nvrsang',
  'nvda go up',
  'lligmah',
  'LLIGMA',
  'lligetlucky',
  'ICDAS'])

## 14. Save the automatically collected Hiscores dataset

The final dataset is saved into the processed data folder.

This file will be used as input for the data cleaning notebook.

In [66]:
output_path = PROCESSED_DATA_DIR / "osrs_hiscores_auto_sample.csv"

df_hiscores.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

output_path

WindowsPath('C:/Projects/osrs-player-segmentation/data/processed/osrs_hiscores_auto_sample.csv')

## Summary

This notebook collected a larger and more diverse OSRS player sample.

The main steps were:

- generating random partial username search terms,
- collecting player names from public player search results,
- removing duplicate usernames,
- downloading public OSRS Hiscores data,
- parsing skill rank, level and experience values,
- saving the final dataset for cleaning and clustering.

The collected sample is not a perfectly random representation of all OSRS players, but it reduces the strong bias that would come from using only top leaderboard players.