# 01b - Automatic Player Collection

The first data collection notebook used a small manually selected player list.

That sample was useful for testing the pipeline, but it is too small and biased for meaningful clustering.

This notebook automatically collects a larger and more diverse set of Old School RuneScape player names using random partial username searches.

After collecting player names, the notebook downloads public OSRS Hiscores data for each player and saves the result as a structured dataset.

## 1. Import required packages

The following packages are used for:

- API requests,
- data handling,
- random search term generation,
- waiting between requests,
- file path management.

In [35]:
import requests
import pandas as pd
import time
import random
import string

from pathlib import Path

## 2. Project paths

The collected dataset will be saved into the `data/processed` folder.

The folder structure follows the project layout used throughout the repository.

In [36]:
## 2. Project paths

The collected dataset will be saved into the `data/processed` folder.

The folder structure follows the project layout used throughout the repository.

SyntaxError: invalid syntax (3039097701.py, line 3)

## 3. Why pseudo-random player collection?

Using only top leaderboard players would introduce strong sampling bias.

Top-ranked players usually have very high levels and similar progression patterns, which would make clustering less meaningful.

Instead, this notebook uses random partial username searches to collect a more diverse set of players.

This is not a perfectly random sample of all OSRS players, but it is more suitable for this project than a top leaderboard sample.

## 4. Generate random username search terms

The player collection process starts by generating random short character combinations.

These terms will be used as partial username searches.

In [37]:
def generate_random_search_terms(
    n_terms=300,
    min_length=2,
    max_length=4,
    random_state=42
):
    """
    Generate random partial username search terms.

    Examples:
    - ab
    - x7
    - kq2
    - 9rs

    These terms are later used to search for OSRS player names.
    """
    random.seed(random_state)

    terms = set()
    characters = string.ascii_lowercase + string.digits

    while len(terms) < n_terms:
        length = random.randint(min_length, max_length)
        term = "".join(random.choice(characters) for _ in range(length))
        terms.add(term)

    return list(terms)

In [38]:
search_terms = generate_random_search_terms(
    n_terms=20,
    min_length=2,
    max_length=4,
    random_state=42
)

search_terms[:10]

['yr9', 'ig', 'yg', '6b', 'fn', '38hy', 'xmec', 'k8pk', 'nre', 'rak']

## 5. Search players by partial username

This function sends a request to the Wise Old Man player search endpoint.

For each random search term, it returns matching player names.

In [39]:
def search_wom_players(username_query, limit=20):
    """
    Search Wise Old Man players by partial username.

    Parameters:
    - username_query: partial username search term
    - limit: maximum number of returned players

    Returns:
    - list of player names
    """
    url = "https://api.wiseoldman.net/v2/players/search"

    params = {
        "username": username_query,
        "limit": limit
    }

    try:
        response = requests.get(url, params=params, timeout=15)
        response.raise_for_status()

        data = response.json()

        player_names = []

        for item in data:
            username = (
                item.get("displayName")
                or item.get("username")
            )

            if username:
                player_names.append(username)

        return player_names

    except requests.RequestException as error:
        print(f"Search failed for query '{username_query}': {error}")
        return []

In [40]:
test_names = search_wom_players("rs", limit=10)

len(test_names), test_names[:10]

(10,
 ['RsSuomi',
  'Rs Jamal',
  'Rs But Afk',
  'rsvp',
  'Rs Wiki',
  'RS SLAG',
  'Rs Kajcsa',
  'rsyux',
  'RS ape',
  'rs basherr'])

## 6. Collect pseudo-random player names

This function repeatedly generates search terms, queries matching players, and stores unique usernames.

The process stops when the target number of unique players is reached or when all search terms have been used.

In [41]:
def collect_pseudo_random_player_names(
    target_count=500,
    n_search_terms=500,
    results_per_term=20,
    sleep_seconds=0.2,
    random_state=42
):
    """
    Collect a diverse set of OSRS player names using random partial username searches.

    Parameters:
    - target_count: desired number of unique player names
    - n_search_terms: number of generated random search terms
    - results_per_term: maximum number of players returned per search term
    - sleep_seconds: waiting time between API requests
    - random_state: seed for reproducibility

    Returns:
    - list of unique player names
    """
    search_terms = generate_random_search_terms(
        n_terms=n_search_terms,
        min_length=2,
        max_length=4,
        random_state=random_state
    )

    collected_names = []

    for index, term in enumerate(search_terms, start=1):
        print(f"[{index}/{len(search_terms)}] Searching term: {term}")

        names = search_wom_players(
            username_query=term,
            limit=results_per_term
        )

        collected_names.extend(names)
        collected_names = list(dict.fromkeys(collected_names))

        print(f"Collected unique players: {len(collected_names)}")

        if len(collected_names) >= target_count:
            break

        time.sleep(sleep_seconds)

    return collected_names[:target_count]

## 7. Run player name collection

In this step, we collect the player names that will be used for Hiscores data collection.

The target sample size can be adjusted depending on runtime.

In [43]:
player_names = collect_pseudo_random_player_names(
    target_count=300,
    n_search_terms=600,
    results_per_term=20,
    sleep_seconds=0.2,
    random_state=42
)

len(player_names), player_names[:20]

[1/600] Searching term: 07
Collected unique players: 20
[2/600] Searching term: q7
Collected unique players: 30
[3/600] Searching term: mdry
Collected unique players: 30
[4/600] Searching term: ka
Collected unique players: 50
[5/600] Searching term: yr0
Collected unique players: 51
[6/600] Searching term: t0hi
Collected unique players: 51
[7/600] Searching term: oe3
Collected unique players: 51
[8/600] Searching term: lie3
Collected unique players: 51
[9/600] Searching term: bwe
Collected unique players: 71
[10/600] Searching term: xxyc
Collected unique players: 71
[11/600] Searching term: n5u4
Collected unique players: 71
[12/600] Searching term: zrad
Collected unique players: 74
[13/600] Searching term: t6z
Collected unique players: 74
[14/600] Searching term: ump
Collected unique players: 94
[15/600] Searching term: qc
Collected unique players: 114
[16/600] Searching term: 830
Collected unique players: 117
[17/600] Searching term: 3w
Collected unique players: 137
[18/600] Searching term: jym6
Collected unique players: 137
[19/600] Searching term: 6cc
Collected unique players: 137
[20/600] Searching term: mq
Collected unique players: 157
[21/600] Searching term: ne
Search failed for query 'ne': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ne&limit=20
Collected unique players: 157
[22/600] Searching term: 6z8v
Search failed for query '6z8v': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6z8v&limit=20
Collected unique players: 157
[23/600] Searching term: 9k
Search failed for query '9k': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=9k&limit=20
Collected unique players: 157
[24/600] Searching term: 1li
Search failed for query '1li': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1li&limit=20
Collected unique players: 157
[25/600] Searching term: j2xx
Search failed for query 'j2xx': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=j2xx&limit=20
Collected unique players: 157
[26/600] Searching term: vu8
Search failed for query 'vu8': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vu8&limit=20
Collected unique players: 157
[27/600] Searching term: z6
Search failed for query 'z6': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=z6&limit=20
Collected unique players: 157
[28/600] Searching term: vdv
Search failed for query 'vdv': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vdv&limit=20
Collected unique players: 157
[29/600] Searching term: zif
Search failed for query 'zif': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=zif&limit=20
Collected unique players: 157
[30/600] Searching term: ct
Search failed for query 'ct': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ct&limit=20
Collected unique players: 157
[31/600] Searching term: l57y
Search failed for query 'l57y': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=l57y&limit=20
Collected unique players: 157
[32/600] Searching term: el53
Search failed for query 'el53': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=el53&limit=20
Collected unique players: 157
[33/600] Searching term: k1
Search failed for query 'k1': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=k1&limit=20
Collected unique players: 157
[34/600] Searching term: tvwa
Search failed for query 'tvwa': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=tvwa&limit=20
Collected unique players: 157
[35/600] Searching term: 7xe
Search failed for query '7xe': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=7xe&limit=20
Collected unique players: 157
[36/600] Searching term: cu
Search failed for query 'cu': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=cu&limit=20
Collected unique players: 157
[37/600] Searching term: afbq
Search failed for query 'afbq': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=afbq&limit=20
Collected unique players: 157
[38/600] Searching term: yp
Search failed for query 'yp': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=yp&limit=20
Collected unique players: 157
[39/600] Searching term: j3d9
Search failed for query 'j3d9': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=j3d9&limit=20
Collected unique players: 157
[40/600] Searching term: mlj
Search failed for query 'mlj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=mlj&limit=20
Collected unique players: 157
[41/600] Searching term: tln
Search failed for query 'tln': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=tln&limit=20
Collected unique players: 157
[42/600] Searching term: x6
Search failed for query 'x6': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=x6&limit=20
Collected unique players: 157
[43/600] Searching term: qxj
Search failed for query 'qxj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=qxj&limit=20
Collected unique players: 157
[44/600] Searching term: 22n
Search failed for query '22n': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=22n&limit=20
Collected unique players: 157
[45/600] Searching term: un5z
Search failed for query 'un5z': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=un5z&limit=20
Collected unique players: 157
[46/600] Searching term: 7f
Search failed for query '7f': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=7f&limit=20
Collected unique players: 157
[47/600] Searching term: 4mpr
Search failed for query '4mpr': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=4mpr&limit=20
Collected unique players: 157
[48/600] Searching term: 0mg
Search failed for query '0mg': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=0mg&limit=20
Collected unique players: 157
[49/600] Searching term: 6nj4
Search failed for query '6nj4': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6nj4&limit=20
Collected unique players: 157
[50/600] Searching term: ne00
Search failed for query 'ne00': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ne00&limit=20
Collected unique players: 157
[51/600] Searching term: i5ga
Search failed for query 'i5ga': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=i5ga&limit=20
Collected unique players: 157
[52/600] Searching term: 6ra
Search failed for query '6ra': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6ra&limit=20
Collected unique players: 157
[53/600] Searching term: s2
Search failed for query 's2': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=s2&limit=20
Collected unique players: 157
[54/600] Searching term: 2fuw
Search failed for query '2fuw': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=2fuw&limit=20
Collected unique players: 157
[55/600] Searching term: yx
Search failed for query 'yx': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=yx&limit=20
Collected unique players: 157

[56/600] Searching term: eiu
Search failed for query 'eiu': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=eiu&limit=20
Collected unique players: 157
[57/600] Searching term: s5
Search failed for query 's5': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=s5&limit=20
Collected unique players: 157
[58/600] Searching term: 72r
Search failed for query '72r': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=72r&limit=20
Collected unique players: 157
[59/600] Searching term: gup3
Search failed for query 'gup3': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=gup3&limit=20
Collected unique players: 157
[60/600] Searching term: hzb
Search failed for query 'hzb': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hzb&limit=20
Collected unique players: 157
[61/600] Searching term: tj
Search failed for query 'tj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=tj&limit=20
Collected unique players: 157
[62/600] Searching term: 1ru
Search failed for query '1ru': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1ru&limit=20
Collected unique players: 157
[63/600] Searching term: 8rvh
Search failed for query '8rvh': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=8rvh&limit=20
Collected unique players: 157
[64/600] Searching term: f8i
Search failed for query 'f8i': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=f8i&limit=20
Collected unique players: 157
[65/600] Searching term: 6k
Search failed for query '6k': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6k&limit=20
Collected unique players: 157
[66/600] Searching term: 71hs
Search failed for query '71hs': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=71hs&limit=20
Collected unique players: 157
[67/600] Searching term: usd
Search failed for query 'usd': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=usd&limit=20
Collected unique players: 157
[68/600] Searching term: vg
Search failed for query 'vg': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vg&limit=20
Collected unique players: 157
[69/600] Searching term: xv9
Search failed for query 'xv9': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=xv9&limit=20
Collected unique players: 157
[70/600] Searching term: c1uq
Search failed for query 'c1uq': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=c1uq&limit=20
Collected unique players: 157
[71/600] Searching term: hig
Search failed for query 'hig': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hig&limit=20
Collected unique players: 157
[72/600] Searching term: e8de
Search failed for query 'e8de': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=e8de&limit=20
Collected unique players: 157
[73/600] Searching term: 99b
Search failed for query '99b': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=99b&limit=20
Collected unique players: 157
[74/600] Searching term: r9a7
Search failed for query 'r9a7': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=r9a7&limit=20
Collected unique players: 157
[75/600] Searching term: th
Search failed for query 'th': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=th&limit=20
Collected unique players: 157
[76/600] Searching term: 05
Search failed for query '05': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=05&limit=20
Collected unique players: 157
[77/600] Searching term: pr2
Search failed for query 'pr2': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=pr2&limit=20
Collected unique players: 157
[78/600] Searching term: zt
Search failed for query 'zt': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=zt&limit=20
Collected unique players: 157
[79/600] Searching term: 0j0
Search failed for query '0j0': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=0j0&limit=20
Collected unique players: 157
[80/600] Searching term: 23sy
Search failed for query '23sy': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=23sy&limit=20
Collected unique players: 157
[81/600] Searching term: mc
Search failed for query 'mc': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=mc&limit=20
Collected unique players: 157
[82/600] Searching term: p2r
Search failed for query 'p2r': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=p2r&limit=20
Collected unique players: 157
[83/600] Searching term: 2919
Search failed for query '2919': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=2919&limit=20
Collected unique players: 157
[84/600] Searching term: fo
Search failed for query 'fo': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=fo&limit=20
Collected unique players: 157
[85/600] Searching term: ysqj
Search failed for query 'ysqj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ysqj&limit=20
Collected unique players: 157
[86/600] Searching term: 82
Search failed for query '82': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=82&limit=20
Collected unique players: 157
[87/600] Searching term: 28
Search failed for query '28': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=28&limit=20
Collected unique players: 157
[88/600] Searching term: 16xb
Search failed for query '16xb': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=16xb&limit=20
Collected unique players: 157
[89/600] Searching term: vfpt
Search failed for query 'vfpt': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vfpt&limit=20
Collected unique players: 157
[90/600] Searching term: vh3
Search failed for query 'vh3': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vh3&limit=20
Collected unique players: 157
[91/600] Searching term: xsy
Search failed for query 'xsy': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=xsy&limit=20
Collected unique players: 157
[92/600] Searching term: pr7
Search failed for query 'pr7': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=pr7&limit=20
Collected unique players: 157
[93/600] Searching term: hgp
Search failed for query 'hgp': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hgp&limit=20
Collected unique players: 157
[94/600] Searching term: hb
Search failed for query 'hb': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hb&limit=20
Collected unique players: 157
[95/600] Searching term: brcl
Search failed for query 'brcl': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=brcl&limit=20
Collected unique players: 157
[96/600] Searching term: b5u
Search failed for query 'b5u': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=b5u&limit=20
Collected unique players: 157

[97/600] Searching term: 4kfs
Search failed for query '4kfs': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=4kfs&limit=20
Collected unique players: 157
[98/600] Searching term: 852f
Search failed for query '852f': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=852f&limit=20
Collected unique players: 157
[99/600] Searching term: 9yv
Search failed for query '9yv': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=9yv&limit=20
Collected unique players: 157
[100/600] Searching term: 1vrj
Search failed for query '1vrj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1vrj&limit=20
Collected unique players: 157
[101/600] Searching term: ren
Search failed for query 'ren': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ren&limit=20
Collected unique players: 157
[102/600] Searching term: j3x
Search failed for query 'j3x': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=j3x&limit=20
Collected unique players: 157
[103/600] Searching term: taq
Search failed for query 'taq': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=taq&limit=20
Collected unique players: 157
[104/600] Searching term: fu
Search failed for query 'fu': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=fu&limit=20
Collected unique players: 157
[105/600] Searching term: cw
Search failed for query 'cw': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=cw&limit=20
Collected unique players: 157
[106/600] Searching term: 361
Search failed for query '361': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=361&limit=20
Collected unique players: 157
[107/600] Searching term: t4b
Search failed for query 't4b': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=t4b&limit=20
Collected unique players: 157
[108/600] Searching term: nnov
Search failed for query 'nnov': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=nnov&limit=20
Collected unique players: 157
[109/600] Searching term: jeir
Search failed for query 'jeir': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=jeir&limit=20
Collected unique players: 157
[110/600] Searching term: 8b
Search failed for query '8b': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=8b&limit=20
Collected unique players: 157
[111/600] Searching term: s9im
Search failed for query 's9im': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=s9im&limit=20
Collected unique players: 157
[112/600] Searching term: edj
Search failed for query 'edj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=edj&limit=20
Collected unique players: 157
[113/600] Searching term: qd
Search failed for query 'qd': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=qd&limit=20
Collected unique players: 157
[114/600] Searching term: mhv
Search failed for query 'mhv': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=mhv&limit=20
Collected unique players: 157
[115/600] Searching term: pm
Search failed for query 'pm': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=pm&limit=20
Collected unique players: 157
[116/600] Searching term: x76r
Search failed for query 'x76r': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=x76r&limit=20
Collected unique players: 157
[117/600] Searching term: fn
Search failed for query 'fn': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=fn&limit=20
Collected unique players: 157
[118/600] Searching term: j1fo
Search failed for query 'j1fo': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=j1fo&limit=20
Collected unique players: 157
[119/600] Searching term: o7y
Search failed for query 'o7y': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=o7y&limit=20
Collected unique players: 157
[120/600] Searching term: os
Search failed for query 'os': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=os&limit=20
Collected unique players: 157
[121/600] Searching term: 043
Search failed for query '043': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=043&limit=20
Collected unique players: 157
[122/600] Searching term: 7cvi
Search failed for query '7cvi': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=7cvi&limit=20
Collected unique players: 157
[123/600] Searching term: m1h
Search failed for query 'm1h': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=m1h&limit=20
Collected unique players: 157
[124/600] Searching term: y4
Search failed for query 'y4': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=y4&limit=20
Collected unique players: 157
[125/600] Searching term: o5or
Search failed for query 'o5or': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=o5or&limit=20
Collected unique players: 157
[126/600] Searching term: 8j
Search failed for query '8j': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=8j&limit=20
Collected unique players: 157
[127/600] Searching term: zfv
Search failed for query 'zfv': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=zfv&limit=20
Collected unique players: 157
[128/600] Searching term: je4q
Search failed for query 'je4q': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=je4q&limit=20
Collected unique players: 157
[129/600] Searching term: fjw
Search failed for query 'fjw': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=fjw&limit=20
Collected unique players: 157
[130/600] Searching term: f7xe
Search failed for query 'f7xe': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=f7xe&limit=20
Collected unique players: 157
[131/600] Searching term: hn5
Search failed for query 'hn5': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hn5&limit=20
Collected unique players: 157
[132/600] Searching term: x6g
Search failed for query 'x6g': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=x6g&limit=20
Collected unique players: 157
[133/600] Searching term: hw1h
Search failed for query 'hw1h': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hw1h&limit=20
Collected unique players: 157
[134/600] Searching term: iqk
Search failed for query 'iqk': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=iqk&limit=20
Collected unique players: 157
[135/600] Searching term: e98s
Search failed for query 'e98s': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=e98s&limit=20
Collected unique players: 157
[136/600] Searching term: g52
Search failed for query 'g52': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=g52&limit=20
Collected unique players: 157
[137/600] Searching term: y2y
Search failed for query 'y2y': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=y2y&limit=20
Collected unique players: 157

[138/600] Searching term: ifet
Search failed for query 'ifet': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ifet&limit=20
Collected unique players: 157
[139/600] Searching term: h3
Search failed for query 'h3': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=h3&limit=20
Collected unique players: 157
[140/600] Searching term: g50r
Search failed for query 'g50r': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=g50r&limit=20
Collected unique players: 157
[141/600] Searching term: cem9
Search failed for query 'cem9': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=cem9&limit=20
Collected unique players: 157
[142/600] Searching term: 73
Search failed for query '73': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=73&limit=20
Collected unique players: 157
[143/600] Searching term: cl0l
Search failed for query 'cl0l': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=cl0l&limit=20
Collected unique players: 157
[144/600] Searching term: 6mww
Search failed for query '6mww': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6mww&limit=20
Collected unique players: 157
[145/600] Searching term: mj
Search failed for query 'mj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=mj&limit=20
Collected unique players: 157
[146/600] Searching term: 03d9
Search failed for query '03d9': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=03d9&limit=20
Collected unique players: 157
[147/600] Searching term: wb0
Search failed for query 'wb0': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=wb0&limit=20
Collected unique players: 157
[148/600] Searching term: 2yv
Search failed for query '2yv': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=2yv&limit=20
Collected unique players: 157
[149/600] Searching term: hx
Search failed for query 'hx': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hx&limit=20
Collected unique players: 157
[150/600] Searching term: 7o
Search failed for query '7o': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=7o&limit=20
Collected unique players: 157
[151/600] Searching term: q9ah
Search failed for query 'q9ah': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=q9ah&limit=20
Collected unique players: 157
[152/600] Searching term: g1
Search failed for query 'g1': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=g1&limit=20
Collected unique players: 157
[153/600] Searching term: he
Search failed for query 'he': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=he&limit=20
Collected unique players: 157
[154/600] Searching term: 6b
Search failed for query '6b': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6b&limit=20
Collected unique players: 157
[155/600] Searching term: 4mx
Search failed for query '4mx': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=4mx&limit=20
Collected unique players: 157
[156/600] Searching term: aq8
Search failed for query 'aq8': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=aq8&limit=20
Collected unique players: 157
[157/600] Searching term: 1k2w
Search failed for query '1k2w': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1k2w&limit=20
Collected unique players: 157
[158/600] Searching term: 6ths
Search failed for query '6ths': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6ths&limit=20
Collected unique players: 157
[159/600] Searching term: tzx2
Search failed for query 'tzx2': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=tzx2&limit=20
Collected unique players: 157
[160/600] Searching term: q3qa
Search failed for query 'q3qa': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=q3qa&limit=20
Collected unique players: 157
[161/600] Searching term: nvnq
Search failed for query 'nvnq': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=nvnq&limit=20
Collected unique players: 157
[162/600] Searching term: q6
Search failed for query 'q6': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=q6&limit=20
Collected unique players: 157
[163/600] Searching term: k2c0
Search failed for query 'k2c0': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=k2c0&limit=20
Collected unique players: 157
[164/600] Searching term: ff5e
Search failed for query 'ff5e': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ff5e&limit=20
Collected unique players: 157
[165/600] Searching term: 8st
Search failed for query '8st': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=8st&limit=20
Collected unique players: 157
[166/600] Searching term: mlz1
Search failed for query 'mlz1': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=mlz1&limit=20
Collected unique players: 157
[167/600] Searching term: yr
Search failed for query 'yr': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=yr&limit=20
Collected unique players: 157
[168/600] Searching term: p3y
Search failed for query 'p3y': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=p3y&limit=20
Collected unique players: 157
[169/600] Searching term: hmb2
Search failed for query 'hmb2': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hmb2&limit=20
Collected unique players: 157
[170/600] Searching term: 2l
Search failed for query '2l': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=2l&limit=20
Collected unique players: 157
[171/600] Searching term: vp
Search failed for query 'vp': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=vp&limit=20
Collected unique players: 157
[172/600] Searching term: nz
Search failed for query 'nz': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=nz&limit=20
Collected unique players: 157
[173/600] Searching term: yzme
Search failed for query 'yzme': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=yzme&limit=20
Collected unique players: 157
[174/600] Searching term: jo3
Search failed for query 'jo3': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=jo3&limit=20
Collected unique players: 157
[175/600] Searching term: l9
Search failed for query 'l9': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=l9&limit=20
Collected unique players: 157
[176/600] Searching term: di7n
Search failed for query 'di7n': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=di7n&limit=20
Collected unique players: 157
[177/600] Searching term: jpgj
Search failed for query 'jpgj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=jpgj&limit=20
Collected unique players: 157
[178/600] Searching term: 8f1c
Search failed for query '8f1c': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=8f1c&limit=20
Collected unique players: 157

[179/600] Searching term: 1a78
Search failed for query '1a78': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1a78&limit=20
Collected unique players: 157
[180/600] Searching term: 1z
Search failed for query '1z': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1z&limit=20
Collected unique players: 157
[181/600] Searching term: bj
Search failed for query 'bj': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=bj&limit=20
Collected unique players: 157
[182/600] Searching term: ds
Search failed for query 'ds': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=ds&limit=20
Collected unique players: 157
[183/600] Searching term: tb
Search failed for query 'tb': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=tb&limit=20
Collected unique players: 157
[184/600] Searching term: 9j1i
Search failed for query '9j1i': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=9j1i&limit=20
Collected unique players: 157
[185/600] Searching term: 2o8p
Search failed for query '2o8p': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=2o8p&limit=20
Collected unique players: 157
[186/600] Searching term: 7o0t
Search failed for query '7o0t': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=7o0t&limit=20
Collected unique players: 157
[187/600] Searching term: sc
Search failed for query 'sc': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=sc&limit=20
Collected unique players: 157
[188/600] Searching term: xcz
Search failed for query 'xcz': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=xcz&limit=20
Collected unique players: 157
[189/600] Searching term: 5sow
Search failed for query '5sow': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=5sow&limit=20
Collected unique players: 157
[190/600] Searching term: hc0b
Search failed for query 'hc0b': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=hc0b&limit=20
Collected unique players: 157
[191/600] Searching term: g2
Search failed for query 'g2': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=g2&limit=20
Collected unique players: 157
[192/600] Searching term: 1g
Search failed for query '1g': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=1g&limit=20
Collected unique players: 157
[193/600] Searching term: dant
Search failed for query 'dant': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=dant&limit=20
Collected unique players: 157
[194/600] Searching term: j5ci
Search failed for query 'j5ci': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=j5ci&limit=20
Collected unique players: 157
[195/600] Searching term: jb
Search failed for query 'jb': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=jb&limit=20
Collected unique players: 157
[196/600] Searching term: nzd
Search failed for query 'nzd': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=nzd&limit=20
Collected unique players: 157
[197/600] Searching term: od4k
Search failed for query 'od4k': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=od4k&limit=20
Collected unique players: 157
[198/600] Searching term: 6a8
Search failed for query '6a8': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=6a8&limit=20
Collected unique players: 157
[199/600] Searching term: d9l
Search failed for query 'd9l': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=d9l&limit=20
Collected unique players: 157
[200/600] Searching term: 9gd
Search failed for query '9gd': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=9gd&limit=20
Collected unique players: 157
[201/600] Searching term: jo
Search failed for query 'jo': 429 Client Error: Too Many Requests for url: https://api.wiseoldman.net/v2/players/search?username=jo&limit=20
Collected unique players: 157
[202/600] Searching term: lta
Collected unique players: 177
[203/600] Searching term: 4eff
Collected unique players: 177
[204/600] Searching term: udd4
Collected unique players: 177
[205/600] Searching term: 8afp
Collected unique players: 177
[206/600] Searching term: hj5
Collected unique players: 179
[207/600] Searching term: ar
Collected unique players: 199
[208/600] Searching term: 4p
Collected unique players: 219
[209/600] Searching term: 195d
Collected unique players: 219
[210/600] Searching term: 98
Collected unique players: 239
[211/600] Searching term: 03v
Collected unique players: 240
[212/600] Searching term: m8
Collected unique players: 260
[213/600] Searching term: uha
Collected unique players: 280
[214/600] Searching term: 3eh5
Collected unique players: 280
[215/600] Searching term: py
Collected unique players: 300

(300,
 ['07 iron',
  '07dive',
  '07 Flare',
  '07 Nihilist',
  '07 Hollyman',
  '07Mana',
  '07Ashley',
  '07wan',
  '07Chris',
  '07 0',
  '07 Preacher',
  '07 tim',
  '07 PRISMA',
  '07 t bone',
  '07Geno',
  '07TroyScape',
  '07 maisy',
  '07 ezra',
  '07 Account',
  '07 Camry'])

## 8. Save collected player names

The collected usernames are saved separately.

This makes the data collection process more reproducible and allows reusing the same player list later.

In [44]:
player_names_path = PROCESSED_DATA_DIR / "osrs_collected_player_names.csv"

pd.DataFrame({"player": player_names}).to_csv(
    player_names_path,
    index=False,
    encoding="utf-8"
)

player_names_path

WindowsPath('C:/Projects/osrs-player-segmentation/data/processed/osrs_collected_player_names.csv')

## 9. Define OSRS Hiscores skill structure

The OSRS Hiscores endpoint returns skill data in a fixed order.

Each skill row contains:

- rank,
- level,
- experience.

The skill list must match the order returned by the Hiscores endpoint.

In [45]:
SKILLS = [
    "overall",
    "attack",
    "defence",
    "strength",
    "hitpoints",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecraft",
    "hunter",
    "construction",
    "sailing"
]

## 10. Fetch OSRS Hiscores data

After collecting player names, this section downloads public OSRS Hiscores data for each player.

In [46]:
def fetch_hiscores(player_name):
    """
    Fetch raw OSRS Hiscores data for a single player.

    Returns:
    - raw text response if successful
    - None if the request fails
    """
    url = "https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws"

    params = {
        "player": player_name
    }

    try:
        response = requests.get(url, params=params, timeout=10)

        if response.status_code == 200:
            return response.text

        print(f"Failed: {player_name} - HTTP {response.status_code}")
        return None

    except requests.RequestException as error:
        print(f"Request error for {player_name}: {error}")
        return None

## 11. Parse Hiscores skill data

The raw Hiscores response is text-based.

This function converts the skill section into a structured Python dictionary.

In [47]:
def parse_skill_data(player_name, raw_text):
    """
    Parse the skill section of OSRS Hiscores data.

    The first rows of the response contain skill data.
    Each row contains:
    rank, level, experience.
    """
    lines = raw_text.strip().splitlines()
    skill_lines = lines[:len(SKILLS)]

    player_data = {
        "player": player_name
    }

    for skill_name, line in zip(SKILLS, skill_lines):
        values = line.split(",")

        if len(values) < 3:
            continue

        rank, level, xp = values[:3]

        player_data[f"{skill_name}_rank"] = int(rank)
        player_data[f"{skill_name}_level"] = int(level)
        player_data[f"{skill_name}_xp"] = int(xp)

    return player_data

## 12. Download Hiscores data for collected players

This step iterates through the collected player list and downloads Hiscores data for each player.

Invalid or unavailable player profiles are skipped.

In [48]:
records = []
failed_players = []

for index, player_name in enumerate(player_names, start=1):
    print(f"[{index}/{len(player_names)}] Fetching Hiscores: {player_name}")

    raw_text = fetch_hiscores(player_name)

    if raw_text is None:
        failed_players.append(player_name)
        continue

    parsed_data = parse_skill_data(player_name, raw_text)
    records.append(parsed_data)

    time.sleep(0.5)

df_hiscores = pd.DataFrame(records)

df_hiscores.head()

[1/300] Fetching Hiscores: 07 iron
[2/300] Fetching Hiscores: 07dive
[3/300] Fetching Hiscores: 07 Flare
[4/300] Fetching Hiscores: 07 Nihilist
[5/300] Fetching Hiscores: 07 Hollyman
[6/300] Fetching Hiscores: 07Mana
[7/300] Fetching Hiscores: 07Ashley
[8/300] Fetching Hiscores: 07wan
[9/300] Fetching Hiscores: 07Chris
[10/300] Fetching Hiscores: 07 0
[11/300] Fetching Hiscores: 07 Preacher
[12/300] Fetching Hiscores: 07 tim
[13/300] Fetching Hiscores: 07 PRISMA
[14/300] Fetching Hiscores: 07 t bone
[15/300] Fetching Hiscores: 07Geno
[16/300] Fetching Hiscores: 07TroyScape
[17/300] Fetching Hiscores: 07 maisy
[18/300] Fetching Hiscores: 07 ezra
[19/300] Fetching Hiscores: 07 Account
[20/300] Fetching Hiscores: 07 Camry
[21/300] Fetching Hiscores: Q7L
[22/300] Fetching Hiscores: q7f
Failed: q7f - HTTP 404
[23/300] Fetching Hiscores: q7d
[24/300] Fetching Hiscores: Q7 1
Failed: Q7 1 - HTTP 404
[25/300] Fetching Hiscores: q7g
[26/300] Fetching Hiscores: q7s
Failed: q7s - HTTP 404
[27/300] Fetching Hiscores: q7
[28/300] Fetching Hiscores: q73
[29/300] Fetching Hiscores: q7a tempest
Failed: q7a tempest - HTTP 404
[30/300] Fetching Hiscores: Q7ls Scout
Failed: Q7ls Scout - HTTP 404
[31/300] Fetching Hiscores: karibola
[32/300] Fetching Hiscores: Karma
[33/300] Fetching Hiscores: Kahvo
[34/300] Fetching Hiscores: kakarot owns
[35/300] Fetching Hiscores: kait
[36/300] Fetching Hiscores: Kaeleen
Failed: Kaeleen - HTTP 404
[37/300] Fetching Hiscores: Kawaiimachin
[38/300] Fetching Hiscores: KalNun
Failed: KalNun - HTTP 404
[39/300] Fetching Hiscores: Kaan
[40/300] Fetching Hiscores: kamille goch
Failed: kamille goch - HTTP 404
[41/300] Fetching Hiscores: Karlteine
[42/300] Fetching Hiscores: kaicenat67
[43/300] Fetching Hiscores: Karl1s
[44/300] Fetching Hiscores: Kacy
[45/300] Fetching Hiscores: Karl
[46/300] Fetching Hiscores: Kappadalism
Failed: Kappadalism - HTTP 404
[47/300] Fetching Hiscores: Katania
[48/300] Fetching Hiscores: Katinas
[49/300] Fetching Hiscores: kapkeik
[50/300] Fetching Hiscores: karilol
[51/300] Fetching Hiscores: yr00bie
[52/300] Fetching Hiscores: Bwent
[53/300] Fetching Hiscores: Bwekfast
[54/300] Fetching Hiscores: bwests
[55/300] Fetching Hiscores: Bwennno
[56/300] Fetching Hiscores: bwexy
[57/300] Fetching Hiscores: bwehhh
[58/300] Fetching Hiscores: Bwekfast IM
[59/300] Fetching Hiscores: Bwena
[60/300] Fetching Hiscores: Bwenne
[61/300] Fetching Hiscores: bweltz
[62/300] Fetching Hiscores: bweakfest
Failed: bweakfest - HTTP 404
[63/300] Fetching Hiscores: bweers
[64/300] Fetching Hiscores: bwenno
Failed: bwenno - HTTP 404
[65/300] Fetching Hiscores: bwenton
Failed: bwenton - HTTP 404
[66/300] Fetching Hiscores: bwesto
[67/300] Fetching Hiscores: Bwently
[68/300] Fetching Hiscores: Bweed7
[69/300] Fetching Hiscores: Bwead Cwust
[70/300] Fetching Hiscores: bwe11sy
[71/300] Fetching Hiscores: Bwenz999
[72/300] Fetching Hiscores: zrad37
[73/300] Fetching Hiscores: ZRadz
[74/300] Fetching Hiscores: zrado
Failed: zrado - HTTP 404
[75/300] Fetching Hiscores: ump45 mw2
[76/300] Fetching Hiscores: umpz
[77/300] Fetching Hiscores: UmPintelho
[78/300] Fetching Hiscores: umph um love
[79/300] Fetching Hiscores: umphreymcgee
[80/300] Fetching Hiscores: UmphrayMcgee
Failed: UmphrayMcgee - HTTP 404
[81/300] Fetching Hiscores: Umprella
Failed: Umprella - HTTP 404
[82/300] Fetching Hiscores: UMP 45
[83/300] Fetching Hiscores: UMP45 Rusher
[84/300] Fetching Hiscores: Umpty
[85/300] Fetching Hiscores: umpppa
[86/300] Fetching Hiscores: umpix
[87/300] Fetching Hiscores: Umper15
[88/300] Fetching Hiscores: Umptieth
[89/300] Fetching Hiscores: umper 15
[90/300] Fetching Hiscores: umpanii
Failed: umpanii - HTTP 404
[91/300] Fetching Hiscores: Umparumpa
[92/300] Fetching Hiscores: umpol
Failed: umpol - HTTP 404
[93/300] Fetching Hiscores: ump45
Failed: ump45 - HTTP 404
[94/300] Fetching Hiscores: Umpihomo
[95/300] Fetching Hiscores: Qc power1
[96/300] Fetching Hiscores: qciz
[97/300] Fetching Hiscores: qcla
[98/300] Fetching Hiscores: qCooP
[99/300] Fetching Hiscores: qc dakar666
[100/300] Fetching Hiscores: QcDip
[101/300] Fetching Hiscores: qcqs
[102/300] Fetching Hiscores: QC 4 Life
[103/300] Fetching Hiscores: Qc Budweiser
[104/300] Fetching Hiscores: qcq
[105/300] Fetching Hiscores: QCKEEF
[106/300] Fetching Hiscores: Qc Elfmage
[107/300] Fetching Hiscores: Qchem
[108/300] Fetching Hiscores: Qc Phosani
[109/300] Fetching Hiscores: Qcid
Failed: Qcid - HTTP 404
[110/300] Fetching Hiscores: QcBobby
[111/300] Fetching Hiscores: Qc99
Failed: Qc99 - HTTP 404
[112/300] Fetching Hiscores: QcShadows
[113/300] Fetching Hiscores: QcJustinGD2
[114/300] Fetching Hiscores: QcRigatoni
[115/300] Fetching Hiscores: 830
[116/300] Fetching Hiscores: 8309
[117/300] Fetching Hiscores: 830M
Failed: 830M - HTTP 404
[118/300] Fetching Hiscores: 3WordName
[119/300] Fetching Hiscores: 3we
[120/300] Fetching Hiscores: 3Wive19Kids
Failed: 3Wive19Kids - HTTP 404
[121/300] Fetching Hiscores: 3wit
[122/300] Fetching Hiscores: 3w87q
[123/300] Fetching Hiscores: 3wrapz3
[124/300] Fetching Hiscores: 3wieler
[125/300] Fetching Hiscores: 3WA3
[126/300] Fetching Hiscores: 3wil
[127/300] Fetching Hiscores: 3w4 b34ch
[128/300] Fetching Hiscores: 3W4N
[129/300] Fetching Hiscores: 3ways
[130/300] Fetching Hiscores: 3wheeltrike
Failed: 3wheeltrike - HTTP 404
[131/300] Fetching Hiscores: 3ws
[132/300] Fetching Hiscores: 3wardbirdgo
[133/300] Fetching Hiscores: 3waycall
[134/300] Fetching Hiscores: 3w3 jutt
Failed: 3w3 jutt - HTTP 404
[135/300] Fetching Hiscores: 3wd
Failed: 3wd - HTTP 404
[136/300] Fetching Hiscores: 3warnec
[137/300] Fetching Hiscores: 3w85t7y4g
Failed: 3w85t7y4g - HTTP 404
[138/300] Fetching Hiscores: Mqven
[139/300] Fetching Hiscores: Mqxyy
[140/300] Fetching Hiscores: mqpc
[141/300] Fetching Hiscores: mqo
[142/300] Fetching Hiscores: MQMQ
[143/300] Fetching Hiscores: mqap
[144/300] Fetching Hiscores: Mqrk
[145/300] Fetching Hiscores: mqrt
[146/300] Fetching Hiscores: Mq p
[147/300] Fetching Hiscores: Mqko
[148/300] Fetching Hiscores: mqxwastaken
Failed: mqxwastaken - HTTP 404
[149/300] Fetching Hiscores: mqty
[150/300] Fetching Hiscores: mqngled
[151/300] Fetching Hiscores: mque
[152/300] Fetching Hiscores: mqrx
[153/300] Fetching Hiscores: Mqn
[154/300] Fetching Hiscores: Mq4
[155/300] Fetching Hiscores: mqpd
[156/300] Fetching Hiscores: mq107
[157/300] Fetching Hiscores: MQLIT
[158/300] Fetching Hiscores: ltachi 01
[159/300] Fetching Hiscores: ltachi X
[160/300] Fetching Hiscores: LTapperz
[161/300] Fetching Hiscores: LtAIdoRalne
[162/300] Fetching Hiscores: ltadori
[163/300] Fetching Hiscores: ltaewon
[164/300] Fetching Hiscores: LtAldoRAlNE
Failed: LtAldoRAlNE - HTTP 404
[165/300] Fetching Hiscores: LTannahill
Failed: LTannahill - HTTP 404
[166/300] Fetching Hiscores: ltami
[167/300] Fetching Hiscores: ltalia
[168/300] Fetching Hiscores: LtAldoRaine3
Failed: LtAldoRaine3 - HTTP 404
[169/300] Fetching Hiscores: ltami alts
[170/300] Fetching Hiscores: Ltabble
[171/300] Fetching Hiscores: ltalians
[172/300] Fetching Hiscores: ltacocatl
[173/300] Fetching Hiscores: LtAldo Rayne
[174/300] Fetching Hiscores: ltakeaseatl
[175/300] Fetching Hiscores: ltachiuchiha
[176/300] Fetching Hiscores: ltachi IM
[177/300] Fetching Hiscores: ltakum
[178/300] Fetching Hiscores: hj56dfd
Failed: hj56dfd - HTTP 404
[179/300] Fetching Hiscores: hj5
Failed: hj5 - HTTP 404
[180/300] Fetching Hiscores: Aryabhata
Failed: Aryabhata - HTTP 404
[181/300] Fetching Hiscores: Aron
[182/300] Fetching Hiscores: Arlind
[183/300] Fetching Hiscores: Arkluccyy
Failed: Arkluccyy - HTTP 404
[184/300] Fetching Hiscores: Ariadna96
[185/300] Fetching Hiscores: Arptastic
[186/300] Fetching Hiscores: ArmadylPker
[187/300] Fetching Hiscores: Arctikus
[188/300] Fetching Hiscores: AriSlash
[189/300] Fetching Hiscores: arrowbob2
[190/300] Fetching Hiscores: ari
[191/300] Fetching Hiscores: Arrazha
[192/300] Fetching Hiscores: artisunj
[193/300] Fetching Hiscores: ari 26
[194/300] Fetching Hiscores: Araur
[195/300] Fetching Hiscores: Aron H
[196/300] Fetching Hiscores: Aradof
[197/300] Fetching Hiscores: Aria on Zeah
[198/300] Fetching Hiscores: Arkhero
[199/300] Fetching Hiscores: ArgyleGrandt
[200/300] Fetching Hiscores: 4pf Taj

[201/300] Fetching Hiscores: 4pf AddMan
[202/300] Fetching Hiscores: 4PF
[203/300] Fetching Hiscores: 4pf Leo
[204/300] Fetching Hiscores: 4pf Big T
[205/300] Fetching Hiscores: 4pf danaw1te
[206/300] Fetching Hiscores: 4pf Gooner
[207/300] Fetching Hiscores: 4pearlpawya
[208/300] Fetching Hiscores: 4peman
[209/300] Fetching Hiscores: 4pf cameron
Failed: 4pf cameron - HTTP 404
[210/300] Fetching Hiscores: 4pf Steve
[211/300] Fetching Hiscores: 4PLATE DEAD
[212/300] Fetching Hiscores: 4pf Eiji
[213/300] Fetching Hiscores: 4pf Danny
Failed: 4pf Danny - HTTP 404
[214/300] Fetching Hiscores: 4pf PvM Lao
[215/300] Fetching Hiscores: 4pf legit
Failed: 4pf legit - HTTP 404
[216/300] Fetching Hiscores: 4pf CaSh
Failed: 4pf CaSh - HTTP 404
[217/300] Fetching Hiscores: 4pf Dracula
Failed: 4pf Dracula - HTTP 404
[218/300] Fetching Hiscores: 4packofpbr
[219/300] Fetching Hiscores: 4pf tady
[220/300] Fetching Hiscores: 98qm8cm8q9mc
Failed: 98qm8cm8q9mc - HTTP 404
[221/300] Fetching Hiscores: 982
[222/300] Fetching Hiscores: 98 RZ
[223/300] Fetching Hiscores: 983 W
Failed: 983 W - HTTP 404
[224/300] Fetching Hiscores: 98 Civic
[225/300] Fetching Hiscores: 9866
[226/300] Fetching Hiscores: 982SF
Failed: 982SF - HTTP 404
[227/300] Fetching Hiscores: 98 Thots
[228/300] Fetching Hiscores: 98 BEDARD
[229/300] Fetching Hiscores: 98 inches
[230/300] Fetching Hiscores: 9898
[231/300] Fetching Hiscores: 98 98
[232/300] Fetching Hiscores: 98slay2175
[233/300] Fetching Hiscores: 98purel
[234/300] Fetching Hiscores: 98x
[235/300] Fetching Hiscores: 987329872410
Failed: 987329872410 - HTTP 404
[236/300] Fetching Hiscores: 98tj
Failed: 98tj - HTTP 404
[237/300] Fetching Hiscores: 98d
[238/300] Fetching Hiscores: 987243682656
Failed: 987243682656 - HTTP 404
[239/300] Fetching Hiscores: 9800X3D
[240/300] Fetching Hiscores: 03v
Failed: 03v - HTTP 404
[241/300] Fetching Hiscores: m8zi
[242/300] Fetching Hiscores: M8A2
[243/300] Fetching Hiscores: M8idgaf
[244/300] Fetching Hiscores: M855A1
[245/300] Fetching Hiscores: M8x Cape
Failed: M8x Cape - HTTP 404
[246/300] Fetching Hiscores: M80 Yoshi
[247/300] Fetching Hiscores: m8t
[248/300] Fetching Hiscores: m8 cheeseman
[249/300] Fetching Hiscores: M84444
[250/300] Fetching Hiscores: m8sn
[251/300] Fetching Hiscores: m87
[252/300] Fetching Hiscores: M8 Cheers
[253/300] Fetching Hiscores: m8g
[254/300] Fetching Hiscores: m8 d
[255/300] Fetching Hiscores: m8bour
[256/300] Fetching Hiscores: m8y pot8y
[257/300] Fetching Hiscores: M8x115
[258/300] Fetching Hiscores: M8
[259/300] Fetching Hiscores: M8w
[260/300] Fetching Hiscores: M8NoFreebies
[261/300] Fetching Hiscores: uHalo
[262/300] Fetching Hiscores: Uhai0123
[263/300] Fetching Hiscores: UhavePackage
[264/300] Fetching Hiscores: Uhaw
Failed: Uhaw - HTTP 404
[265/300] Fetching Hiscores: Uhaveamass
[266/300] Fetching Hiscores: Uhaul
[267/300] Fetching Hiscores: Uha964
[268/300] Fetching Hiscores: uhavenoarms
[269/300] Fetching Hiscores: UHaveMeDazed
[270/300] Fetching Hiscores: Uhavedowns
[271/300] Fetching Hiscores: Uhai
[272/300] Fetching Hiscores: Uha88
[273/300] Fetching Hiscores: uhaul gf
[274/300] Fetching Hiscores: UHAL
[275/300] Fetching Hiscores: uhachapa
Failed: uhachapa - HTTP 404
[276/300] Fetching Hiscores: uHashbrown
[277/300] Fetching Hiscores: uhaverona
[278/300] Fetching Hiscores: Uhanon
[279/300] Fetching Hiscores: UHAVESMALPP
[280/300] Fetching Hiscores: uhavetumor
Failed: uhavetumor - HTTP 404
[281/300] Fetching Hiscores: pyari larki
Failed: pyari larki - HTTP 404
[282/300] Fetching Hiscores: Pyyli
[283/300] Fetching Hiscores: pyon pyon
[284/300] Fetching Hiscores: Pyykki
Failed: Pyykki - HTTP 404
[285/300] Fetching Hiscores: pyip
[286/300] Fetching Hiscores: Pyromanimak
[287/300] Fetching Hiscores: PyroBlaZe
[288/300] Fetching Hiscores: Pyttyyn
[289/300] Fetching Hiscores: Pyro btw
[290/300] Fetching Hiscores: Pyewb
[291/300] Fetching Hiscores: Pyres Ashes
[292/300] Fetching Hiscores: PyroEagle13
[293/300] Fetching Hiscores: Pyrez
[294/300] Fetching Hiscores: Pyromancer
[295/300] Fetching Hiscores: Pyia
[296/300] Fetching Hiscores: Pyux
[297/300] Fetching Hiscores: pyro4ever
[298/300] Fetching Hiscores: pyrocaster
[299/300] Fetching Hiscores: pyronrive
[300/300] Fetching Hiscores: PyScript

,player,overall_rank,overall_level,overall_xp,attack_rank,attack_level,attack_xp,defence_rank,defence_level,defence_xp,...,runecraft_xp,hunter_rank,hunter_level,hunter_xp,construction_rank,construction_level,construction_xp,sailing_rank,sailing_level,sailing_xp
0,07 iron,382,2376,2186969492,1074,99,143756881,769,99,136216686,...,19572847,1960,99,70536444,443,99,34820520,12219,99,14164922
1,07dive,165,2376,3120241113,1678,99,110662107,949,99,115594812,...,46120817,1188,99,90675595,318,99,56103409,24224,99,13130933
2,07 Flare,66407,2341,593892412,40984,99,29757504,39589,99,24209970,...,14707818,55304,99,14340193,57144,99,13251248,299490,64,422540
3,07 Nihilist,106600,2278,646176615,20348,99,38454575,20340,99,29791019,...,13336934,115023,99,13087926,19946,99,13577899,-1,1,0
4,07 Hollyman,22611,2376,550419287,32283,99,32447653,36388,99,24831178,...,13116186,60220,99,14030170,98244,99,13131220,30350,99,13069755

## 13. Inspect collected Hiscores dataset

Before saving the dataset, basic checks are performed.

In [49]:
df_hiscores.shape

(248, 76)

In [50]:
df_hiscores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 76 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   player              248 non-null    object
 1   overall_rank        248 non-null    int64
 2   overall_level       248 non-null    int64
 3   overall_xp          248 non-null    int64
 4   attack_rank         248 non-null    int64
 5   attack_level        248 non-null    int64
 6   attack_xp           248 non-null    int64
 7   defence_rank        248 non-null    int64
 8   defence_level       248 non-null    int64
 9   defence_xp          248 non-null    int64
 10  strength_rank       248 non-null    int64
 11  strength_level      248 non-null    int64
 12  strength_xp         248 non-null    int64
 13  hitpoints_rank      248 non-null    int64
 14  hitpoints_level     248 non-null    int64
 15  hitpoints_xp        248 non-null    int64
 16  ranged_rank         248 non-null    int64
 17  ranged_level        248 non-null    int64
 18  ranged_xp           248 non-null    int64
 19  prayer_rank         248 non-null    int64
 20  prayer_level        248 non-null    int64
 21  prayer_xp           248 non-null    int64
 22  magic_rank          248 non-null    int64
 23  magic_level         248 non-null    int64
 24  magic_xp            248 non-null    int64
 25  cooking_rank        248 non-null    int64
 26  cooking_level       248 non-null    int64
 27  cooking_xp          248 non-null    int64
 28  woodcutting_rank    248 non-null    int64
 29  woodcutting_level   248 non-null    int64
 30  woodcutting_xp      248 non-null    int64
 31  fletching_rank      248 non-null    int64
 32  fletching_level     248 non-null    int64
 33  fletching_xp        248 non-null    int64
 34  fishing_rank        248 non-null    int64
 35  fishing_level       248 non-null    int64
 36  fishing_xp          248 non-null    int64
 37  firemaking_rank     248 non-null    int64
 38  firemaking_level    248 non-null    int64
 39  firemaking_xp       248 non-null    int64
 40  crafting_rank       248 non-null    int64
 41  crafting_level      248 non-null    int64
 42  crafting_xp         248 non-null    int64
 43  smithing_rank       248 non-null    int64
 44  smithing_level      248 non-null    int64
 45  smithing_xp         248 non-null    int64
 46  mining_rank         248 non-null    int64
 47  mining_level        248 non-null    int64
 48  mining_xp           248 non-null    int64
 49  herblore_rank       248 non-null    int64
 50  herblore_level      248 non-null    int64
 51  herblore_xp         248 non-null    int64
 52  agility_rank        248 non-null    int64
 53  agility_level       248 non-null    int64
 54  agility_xp          248 non-null    int64
 55  thieving_rank       248 non-null    int64
 56  thieving_level      248 non-null    int64
 57  thieving_xp         248 non-null    int64
 58  slayer_rank         248 non-null    int64
 59  slayer_level        248 non-null    int64
 60  slayer_xp           248 non-null    int64
 61  farming_rank        248 non-null    int64
 62  farming_level       248 non-null    int64
 63  farming_xp          248 non-null    int64
 64  runecraft_rank      248 non-null    int64
 65  runecraft_level     248 non-null    int64
 66  runecraft_xp        248 non-null    int64
 67  hunter_rank         248 non-null    int64
 68  hunter_level        248 non-null    int64
 69  hunter_xp           248 non-null    int64
 70  construction_rank   248 non-null    int64
 71  construction_level  248 non-null    int64
 72  construction_xp     248 non-null    int64
 73  sailing_rank        248 non-null    int64
 74  sailing_level       248 non-null    int64
 75  sailing_xp          248 non-null    int64
dtypes: int64(75), object(1)
memory usage: 147.4+ KB

In [51]:
df_hiscores.head()

,player,overall_rank,overall_level,overall_xp,attack_rank,attack_level,attack_xp,defence_rank,defence_level,defence_xp,...,runecraft_xp,hunter_rank,hunter_level,hunter_xp,construction_rank,construction_level,construction_xp,sailing_rank,sailing_level,sailing_xp
0,07 iron,382,2376,2186969492,1074,99,143756881,769,99,136216686,...,19572847,1960,99,70536444,443,99,34820520,12219,99,14164922
1,07dive,165,2376,3120241113,1678,99,110662107,949,99,115594812,...,46120817,1188,99,90675595,318,99,56103409,24224,99,13130933
2,07 Flare,66407,2341,593892412,40984,99,29757504,39589,99,24209970,...,14707818,55304,99,14340193,57144,99,13251248,299490,64,422540
3,07 Nihilist,106600,2278,646176615,20348,99,38454575,20340,99,29791019,...,13336934,115023,99,13087926,19946,99,13577899,-1,1,0
4,07 Hollyman,22611,2376,550419287,32283,99,32447653,36388,99,24831178,...,13116186,60220,99,14030170,98244,99,13131220,30350,99,13069755

In [52]:
len(failed_players), failed_players[:20]

(52,
 ['q7f',
  'Q7 1',
  'q7s',
  'q7a tempest',
  'Q7ls Scout',
  'Kaeleen',
  'KalNun',
  'kamille goch',
  'Kappadalism',
  'bweakfest',
  'bwenno',
  'bwenton',
  'zrado',
  'UmphrayMcgee',
  'Umprella',
  'umpanii',
  'umpol',
  'ump45',
  'Qcid',
  'Qc99'])

## 14. Save the automatically collected Hiscores dataset

The final dataset is saved into the processed data folder.

This file will be used as input for the data cleaning notebook.

In [53]:
output_path = PROCESSED_DATA_DIR / "osrs_hiscores_auto_sample.csv"

df_hiscores.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

output_path

WindowsPath('C:/Projects/osrs-player-segmentation/data/processed/osrs_hiscores_auto_sample.csv')

## Summary

This notebook collected a larger and more diverse OSRS player sample.

The main steps were:

- generating random partial username search terms,
- collecting player names from public player search results,
- removing duplicate usernames,
- downloading public OSRS Hiscores data,
- parsing skill rank, level and experience values,
- saving the final dataset for cleaning and clustering.

The collected sample is not a perfectly random representation of all OSRS players, but it reduces the strong bias that would come from using only top leaderboard players.